// WEST COAST + MOUNTAIN BATCH: 8 states. California already exists.

  {
    slug: 'washington',
    name: 'Washington',
    abbreviation: 'WA',
    region: 'great-plains',
    licensingAgency: 'Washington State Department of Agriculture (WSDA)',
    licensingAgencyUrl: 'https://agr.wa.gov',
    aerialCategory: 'No standalone aerial category. Certify in relevant use category + Laws and Safety exam.',
    examsRequired: 'Laws and Safety + use category (2 exams minimum). $25 paper or $58 computer. License $250/yr.',
    examFees: '$25 paper exam or $58 computer. $250/yr commercial license.',
    uniqueRules: [
      'No standalone aerial category; simplest licensing pathway in the West.',
      'WSDA published dedicated drone guidance confirming drones legal wherever airblast is legal.',
      'Certification and Training rule change effective January 1, 2026 updated exam categories.',
      'Most extensive reciprocal licensing chart among all states.',
    ],
    reciprocityStates: ['OR', 'ID', 'MT', 'ND', 'NE', 'MN'],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'Approved CE courses or re-exam per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://agr.wa.gov',
    extensionUrl: 'https://extension.wsu.edu',
    topCrops: [
      { slug: 'orchards', name: 'Apples/Cherries', acreage: '175K acres', notes: '#1 apple state. WSU reports 95% grower interest in drones.' },
      { slug: 'grapes', name: 'Wine Grapes', acreage: '60K acres', notes: 'Columbia Valley, Walla Walla' },
      { slug: 'wheat', name: 'Wheat', acreage: '2.1M acres', notes: 'Palouse region' },
    ],
    rateRange: '$14 to $28',
    neighboringStates: ['oregon', 'idaho'],
    description: 'Washington has the simplest aerial licensing pathway in the West (no standalone aerial category) and published drone guidance confirming drones are legal wherever airblast is legal. #1 apple state with 95% grower interest in drone spraying.',
    aeoBlock: 'Washington has no standalone aerial applicator category, making it the simplest licensing pathway in the West: just Laws and Safety plus a use category exam. WSDA published drone-specific guidance confirming drones are legal wherever airblast is legal. Rates run $14 to $28 per acre across 175K acres of apples and cherries, 60K acres of wine grapes, and 2.1 million acres of wheat.',
    faqs: [
      { question: 'Why is Washington licensing simpler than other states?', answer: 'WSDA does not maintain a standalone aerial category. Drone operators certify in the relevant use category (agricultural, right-of-way, etc.) plus Laws and Safety, making the minimum just 2 exams versus 3 or more in most states.' },
      { question: 'What does drone spraying cost in Washington?', answer: 'Wheat runs $14 to $18 per acre. Apple and cherry orchards run $20 to $28. Wine grapes $18 to $25. The range reflects the mix of flat Palouse wheat and steep hillside tree fruit.' },
      { question: 'Can drones spray Washington apple orchards?', answer: 'Yes. WSU surveys report 95% of apple growers are interested in drone spraying. Hillside blocks in the Wenatchee and Okanogan valleys are the primary opportunity. Dense mid-season canopy on mature trees still benefits from supplemental airblast.' },
      { question: 'Did licensing rules change in 2026?', answer: 'Yes. The WSDA Certification and Training rule change effective January 1, 2026 updated exam categories and study materials. New licensees after that date take updated exams with new manuals.' },
      { question: 'Does Washington have reciprocal licensing?', answer: 'Yes, the most extensive reciprocal chart among all states. Check WSDA online tool for specific category recognition by state.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbreviation: 'OR',
    region: 'great-plains',
    licensingAgency: 'Oregon Department of Agriculture (ODA)',
    licensingAgencyUrl: 'https://www.oregon.gov/oda',
    aerialCategory: 'Aerial Pesticide Applicator (APA) license, a separate standalone add-on.',
    examsRequired: 'Core + use category + APA. 50 hours flight experience required before APA application.',
    examFees: 'Fees per ODA schedule. APA license fee applies.',
    uniqueRules: [
      'APA is a separate add-on license on top of underlying applicator license.',
      '50 hours of flight experience applying pesticides or supervised training required before APA application.',
      'Violation of law to apply any pesticide by aircraft (including drones) without APA, even under supervision.',
      'Oregon Forest Practices Act: 60-foot buffer from fish-bearing streams for non-helicopter aerial (includes drones).',
      'ODA published bilingual (English/Spanish) drone licensing guide.',
    ],
    reciprocityStates: [],
    renewalCycle: '5-year cycle.',
    ceRequirements: '10 aerial credits per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://www.oregon.gov/oda',
    extensionUrl: 'https://extension.oregonstate.edu',
    topCrops: [
      { slug: 'grapes', name: 'Wine Grapes', acreage: '35K acres', notes: 'Willamette Valley' },
      { slug: 'orchards', name: 'Pears/Cherries', acreage: '25K acres', notes: 'Hood River, Rogue Valley' },
      { slug: 'wheat', name: 'Wheat', acreage: '800K acres', notes: 'Eastern Oregon' },
    ],
    rateRange: '$16 to $30',
    neighboringStates: ['washington', 'idaho', 'california', 'nevada'],
    description: 'Oregon has the strictest aerial licensing in the West: 50 hours of flight experience required before even applying for the APA license. It is illegal to spray by drone without an APA, even under supervision of a licensed APA holder.',
    aeoBlock: 'Oregon imposes the strictest aerial licensing in the West, requiring 50 hours of flight experience before applying for the Aerial Pesticide Applicator (APA) license. It is a violation to spray by drone without APA, even under supervision. Rates run $16 to $30 per acre across wine grapes in the Willamette Valley and orchards in Hood River.',
    faqs: [
      { question: 'What is the 50-hour flight experience requirement?', answer: 'Before applying for the APA license, you must document 50 hours of applying pesticides or training to do so under supervision of a licensed APA. This is among the highest flight-hour barriers in the US.' },
      { question: 'Can I spray under supervision while getting my hours?', answer: 'No. Oregon law explicitly prohibits applying any pesticide by aircraft without an APA license, even when operating under direct supervision of a licensed APA holder. You must log your 50 hours as training, not paid commercial work.' },
      { question: 'What does drone spraying cost in Oregon?', answer: 'Wine grapes $22 to $30 per acre. Orchards (pears, cherries) $20 to $28. Wheat $14 to $18. Higher than Washington due to fewer operators and stricter licensing.' },
      { question: 'What are the stream buffer rules?', answer: 'Oregon Forest Practices Act establishes 60-foot buffer zones from fish-bearing or drinking water streams for non-helicopter aerial applications, which includes drones and fixed-wing aircraft.' },
      { question: 'Does Oregon have reciprocal licensing?', answer: 'Case-by-case basis for aerial applicators from other states. No blanket reciprocity agreements. Contact ODA.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'idaho',
    name: 'Idaho',
    abbreviation: 'ID',
    region: 'great-plains',
    licensingAgency: 'Idaho State Department of Agriculture (ISDA)',
    licensingAgencyUrl: 'https://agri.idaho.gov/pesticides/applicator-licensing-certification',
    aerialCategory: 'Category AA: Aerial Applicators',
    examsRequired: 'Core (CO) + Category AA. $120 license. 70% passing.',
    examFees: '$120 license fee.',
    uniqueRules: [
      'Category AA is a clean, straightforward aerial category.',
      'Buffer zone compliance and record-keeping required.',
    ],
    reciprocityStates: ['WA', 'OR', 'MT'],
    renewalCycle: '2-year cycle.',
    ceRequirements: '16 credits per 2-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.uidaho.edu/extension',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '1.2M acres', notes: 'Palouse region shared with WA' },
      { slug: 'corn', name: 'Corn', acreage: '200K acres', notes: 'Magic Valley irrigated' },
    ],
    rateRange: '$14 to $22',
    neighboringStates: ['washington', 'oregon', 'montana', 'wyoming', 'utah', 'nevada'],
    description: 'Idaho has a clean Category AA (Aerial Applicators) licensing pathway with $120 license fee. Palouse wheat and Magic Valley irrigated crops drive primary demand.',
    aeoBlock: 'Idaho uses Category AA (Aerial Applicators) with a straightforward $120 license and 70 percent passing score. Rates run $14 to $22 per acre across 1.2 million acres of Palouse wheat and irrigated crops in the Magic Valley.',
    faqs: [
      { question: 'What does drone spraying cost in Idaho?', answer: 'Wheat runs $14 to $18. Irrigated crops in the Magic Valley $16 to $22. Orchard and vineyard work in the Snake River AVA runs higher.' },
      { question: 'What license do I need in Idaho?', answer: 'FAA Part 107, Part 137, and ISDA Core (CO) + Category AA (Aerial Applicators). $120 license fee. 70% passing.' },
      { question: 'Does Idaho have reciprocal licensing?', answer: 'Yes, with WA, OR, and MT using national standard categories.' },
      { question: 'When is peak spray season in Idaho?', answer: 'Wheat heading in June (Palouse). Potato and sugar beet applications in the Magic Valley June through August.' },
      { question: 'Is there drone spray demand for potatoes?', answer: 'Growing. Idaho grows 300K+ acres of potatoes, and late blight management with drone fungicide is an emerging use case, especially on irrigated fields where pivot tracks limit ground rig access.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    abbreviation: 'NV',
    region: 'great-plains',
    licensingAgency: 'Nevada Department of Agriculture (NDA)',
    licensingAgencyUrl: 'https://agri.nv.gov',
    aerialCategory: 'Core + Laws + Category (3 exams)',
    examsRequired: 'Core + Laws + Category. $50/initial exam. Business license $250/yr.',
    examFees: '$50/initial exam. $250/yr business license.',
    uniqueRules: [
      'Business license at $250/yr.',
      'Very limited agricultural acreage.',
    ],
    reciprocityStates: [],
    renewalCycle: '4-year cycle (certified). Annual (licensed pest control).',
    ceRequirements: '12 CEUs per 4-year cycle (certified). 6 CEUs/yr (licensed).',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.unr.edu',
    topCrops: [],
    rateRange: '$18 to $30',
    neighboringStates: ['california', 'oregon', 'idaho', 'utah', 'arizona'],
    description: 'Nevada has very limited agricultural crop acreage. Primary drone opportunities are in alfalfa hay, ranch rangeland, and cannabis cultivation where permitted.',
    aeoBlock: 'Nevada has minimal agricultural crop acreage with rates of $18 to $30 per acre. Primary drone opportunities are alfalfa hay in the northern valleys and ranch rangeland applications. Business license is $250 per year.',
    faqs: [
      { question: 'Is there drone spray demand in Nevada?', answer: 'Very limited for traditional agriculture. Alfalfa hay in northern Nevada, ranch rangeland, and some cannabis cultivation are the main opportunities.' },
      { question: 'What does drone spraying cost in Nevada?', answer: '$18 to $30 per acre. Higher than neighboring states due to remote locations, small acreage, and very few operators.' },
      { question: 'What license do I need?', answer: 'FAA Part 107, Part 137, and NDA certification with Core + Laws + Category exams. $50 per exam. $250/yr business license.' },
      { question: 'Does Nevada have reciprocal licensing?', answer: 'Not documented. Contact NDA.' },
      { question: 'Is Nevada worth entering as a drone spray market?', answer: 'Only as a secondary market for operators based in neighboring states (CA, ID, UT). The total addressable acreage is too small to support a Nevada-only drone spray business.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbreviation: 'UT',
    region: 'great-plains',
    licensingAgency: 'Utah Department of Agriculture and Food (UDAF)',
    licensingAgencyUrl: 'https://ag.utah.gov/pesticides/apply-or-renew',
    aerialCategory: 'Category 11: Aerial Application. "Special qualifications" for aerial beyond standard exam.',
    examsRequired: 'Core + Category 11 + use category (3 exams). License $65/3yr. $15 per additional category.',
    examFees: '$65 license for 3 years. $15 per additional category.',
    uniqueRules: [
      '"Special qualifications" required for aerial category beyond standard exam.',
      'Must carry license at all times during application.',
      'Aerial Application Study Guide published by UDAF.',
    ],
    reciprocityStates: ['CO', 'ID', 'NV'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '24 CEUs per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://ag.utah.gov/documents/AerialApplicationStudyGuide.pdf',
    extensionUrl: 'https://extension.usu.edu',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '200K acres', notes: 'Northern UT' },
    ],
    rateRange: '$16 to $25',
    neighboringStates: ['idaho', 'wyoming', 'colorado', 'nevada', 'arizona'],
    description: 'Utah requires "special qualifications" for aerial applicators beyond the standard exam and publishes an Aerial Application Study Guide. Agricultural acreage is limited, with alfalfa, wheat, and fruit orchards as primary markets.',
    aeoBlock: 'Utah requires "special qualifications" for Category 11 (Aerial Application) beyond the standard exam, with a published Aerial Application Study Guide. License is $65 for 3 years. Primary drone markets are alfalfa, wheat, and fruit orchards in northern Utah. Rates run $16 to $25 per acre.',
    faqs: [
      { question: 'What are the "special qualifications" for aerial in Utah?', answer: 'UDAF requires additional qualifications beyond the standard Category 11 exam for aerial applicators. Details are in the UDAF Aerial Application Study Guide. Contact UDAF for current specifics.' },
      { question: 'What does drone spraying cost in Utah?', answer: '$16 to $25 per acre. Higher than the Great Plains due to smaller fields and mountainous terrain limiting operational efficiency.' },
      { question: 'What crops use drones in Utah?', answer: 'Alfalfa hay (600K acres), wheat (200K acres), tart cherries in Utah County, and sweet corn in Cache Valley. Ranch rangeland is a secondary market.' },
      { question: 'Does Utah have reciprocal licensing?', answer: 'General provision for reciprocity. Contact UDAF for specific states.' },
      { question: 'Is there a study guide for the aerial exam?', answer: 'Yes. UDAF publishes an Aerial Application Study Guide available at ag.utah.gov.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbreviation: 'AZ',
    region: 'great-plains',
    licensingAgency: 'Arizona Department of Agriculture (AZDA)',
    licensingAgencyUrl: 'https://agriculture.az.gov',
    aerialCategory: 'Drone Pilot License (DPL), separate from Agricultural Aircraft Pilot License (AAP)',
    examsRequired: 'DPL exam (flight procedures, calibration, sensitive areas) + Commercial Applicator Certification (PUC) + Custom Applicator License (CAL $100/yr if for-hire). DPL $50/yr.',
    examFees: 'DPL $50/yr. CAL $100/yr for for-hire work.',
    uniqueRules: [
      'Arizona has a dedicated Drone Pilot License (DPL), separate from the manned Aircraft Pilot License.',
      'Operating without DPL is a nonserious violation under R3-3-502.',
      'Tribal lands may require additional operational permissions beyond state licensing.',
      'DPL requires valid FAA Part 107.',
    ],
    reciprocityStates: [],
    renewalCycle: 'Annual (DPL).',
    ceRequirements: 'Contact AZDA.',
    droneSpecificCredential: true,
    droneGuidanceUrl: 'https://agriculture.az.gov',
    extensionUrl: 'https://extension.arizona.edu',
    topCrops: [
      { slug: 'cotton', name: 'Cotton', acreage: '150K acres', notes: 'Pima and Maricopa counties' },
    ],
    rateRange: '$16 to $28',
    neighboringStates: ['california', 'nevada', 'utah', 'new-mexico'],
    description: 'Arizona is one of the few states with a dedicated Drone Pilot License (DPL), separate from the manned aircraft license. Tribal lands may require additional permissions. Cotton, citrus, and date palms drive the primary demand.',
    aeoBlock: 'Arizona requires a dedicated Drone Pilot License (DPL) at $50 per year, separate from the manned Agricultural Aircraft Pilot License. Operating without DPL is a regulatory violation. Cotton (150K acres), citrus, and date palms drive drone demand. Tribal lands may require additional operational permissions.',
    faqs: [
      { question: 'What is the Arizona Drone Pilot License?', answer: 'A dedicated credential separate from the manned aircraft pilot license. It requires valid FAA Part 107, a written exam on flight procedures, calibration, and operations near sensitive areas, and $50 annual fee. Operating without it is a violation under R3-3-502.' },
      { question: 'What does drone spraying cost in Arizona?', answer: '$16 to $28 per acre. Cotton defoliant and citrus insecticide at the high end. Desert terrain and heat limit daily spray windows to early morning hours.' },
      { question: 'Do tribal lands require extra permissions?', answer: 'Potentially, yes. Arizona extensive tribal lands may require additional operational permissions beyond state DOA licensing. Contact the relevant tribal authority before scheduling work on tribal land.' },
      { question: 'What crops use drones in Arizona?', answer: 'Cotton (150K acres in Pima and Maricopa counties), citrus in the Salt River Valley, date palms in Yuma, and irrigated alfalfa.' },
      { question: 'Does Arizona have reciprocal licensing?', answer: 'Not documented for the DPL. Contact AZDA.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'alaska',
    name: 'Alaska',
    abbreviation: 'AK',
    region: 'great-plains',
    licensingAgency: 'Alaska Department of Environmental Conservation (DEC)',
    licensingAgencyUrl: 'https://dec.alaska.gov',
    aerialCategory: 'Contact DEC. FAA Part 107 required. Liability insurance required.',
    examsRequired: 'Contact DEC for current exam requirements.',
    examFees: 'Contact DEC.',
    uniqueRules: [
      'Minimal agricultural crop acreage.',
      'Primary opportunities in forestry, mosquito control, and invasive species management.',
      'Remote locations add significant logistics cost.',
    ],
    reciprocityStates: [],
    renewalCycle: 'Contact DEC.',
    ceRequirements: 'Contact DEC.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.uaf.edu/ces',
    topCrops: [],
    rateRange: '$25 to $50',
    neighboringStates: [],
    description: 'Alaska has minimal agricultural crop acreage. Drone opportunities center on forestry, mosquito control, and invasive species management. Remote locations drive rates of $25 to $50 per acre.',
    aeoBlock: 'Alaska has minimal agricultural crop acreage with drone opportunities primarily in forestry, mosquito control, and invasive species management. Remote locations drive rates of $25 to $50 per acre. Contact Alaska DEC for current licensing requirements.',
    faqs: [
      { question: 'Is there agricultural drone demand in Alaska?', answer: 'Very limited for traditional crops. Opportunities exist in forestry pest management, mosquito control programs, and invasive species treatment on public lands.' },
      { question: 'What does drone spraying cost in Alaska?', answer: '$25 to $50 per acre. Remote logistics, short growing season, and limited operator base drive rates far above the national average.' },
      { question: 'What license do I need?', answer: 'FAA Part 107, Part 137, liability insurance, and Alaska DEC pesticide certification. Contact DEC directly for current exam and fee requirements.' },
      { question: 'Is Alaska practical for a drone spray business?', answer: 'Only as a specialized niche. Total addressable acreage is too small for a standalone ag drone business. Operators typically combine drone work with other aviation or pest control services.' },
      { question: 'Does Alaska have reciprocal licensing?', answer: 'Not documented. Contact DEC.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    abbreviation: 'HI',
    region: 'great-plains',
    licensingAgency: 'Hawaii Department of Agriculture, Division of Animal and Biocontrol (DAB)',
    licensingAgencyUrl: 'https://dab.hawaii.gov/pi/pest',
    aerialCategory: 'Category 4: Aerial Pest Control. RUP Aerial Permit (Form P-23) also required.',
    examsRequired: 'Core + Category 4. $50/exam. $100 initial cert card.',
    examFees: '$50/exam. $100 initial certification card.',
    uniqueRules: [
      'RUP Aerial Permit (Form P-23) required for restricted-use aerial applications, separate from applicator certification.',
      'RUP buffer zones apply.',
      '75% cap on online CE credits.',
    ],
    reciprocityStates: [],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'CET credits vary. 75% online cap.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.ctahr.hawaii.edu',
    topCrops: [],
    rateRange: '$20 to $40',
    neighboringStates: [],
    description: 'Hawaii requires a separate RUP Aerial Permit (Form P-23) for restricted-use aerial applications. Primary drone opportunities are in coffee, macadamia, tropical fruit, and invasive species management.',
    aeoBlock: 'Hawaii requires Category 4 (Aerial Pest Control) plus a separate RUP Aerial Permit (Form P-23) for restricted-use applications. Primary drone markets are coffee, macadamia nut, tropical fruit, and invasive species management. Rates run $20 to $40 per acre.',
    faqs: [
      { question: 'What is the RUP Aerial Permit?', answer: 'Form P-23, a separate permit required for any aerial application of restricted-use pesticides in Hawaii. This is in addition to your Category 4 applicator certification. Standard permits are for individual applications.' },
      { question: 'What crops use drones in Hawaii?', answer: 'Coffee (Big Island), macadamia nuts, tropical fruit (papaya, banana, pineapple), and seed corn operations on Maui and Molokai. Invasive species management on conservation lands is a growing niche.' },
      { question: 'What does drone spraying cost in Hawaii?', answer: '$20 to $40 per acre. Island logistics (shipping equipment, inter-island travel) and small field sizes push rates well above mainland averages.' },
      { question: 'Are there special buffer zone rules?', answer: 'Yes. Hawaii applies RUP buffer zones for aerial applications near residential areas, schools, and water bodies. These apply to drones as well as manned aircraft.' },
      { question: 'Does Hawaii have reciprocal licensing?', answer: 'No. All operators must test in Hawaii regardless of mainland credentials.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
