// CORN BELT BATCH: Add these 9 state objects to the states array in src/data/states.ts
// Iowa, Texas, California already exist. Append these after them.

  {
    slug: 'illinois',
    name: 'Illinois',
    abbreviation: 'IL',
    region: 'corn-belt',
    licensingAgency: 'Illinois Department of Agriculture (IDA)',
    licensingAgencyUrl: 'https://agr.illinois.gov/pesticides/certification-and-licensing.html',
    aerialCategory: 'Aerial General Standards (replaces Core exam) + site categories',
    examsRequired: 'Aerial General Standards (100 questions, 70%) + category exam (50 questions, 70%)',
    examFees: '$300 commercial license, 3-year term',
    uniqueRules: [
      'Illinois uses an Aerial General Standards exam that replaces the standard Core exam for aerial applicators.',
      'No continuing education option. Must re-test every 3 years to maintain certification.',
      'DriftWatch registry participation recommended.',
    ],
    reciprocityStates: ['IA', 'IN', 'MO', 'WI', 'KY'],
    renewalCycle: '3-year cycle. Re-examination required (no CE alternative).',
    ceRequirements: 'None. Must pass exams again every 3 years.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://extension.illinois.edu/psep/special-licensing',
    extensionUrl: 'https://extension.illinois.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '11M acres', notes: 'VT/R1 fungicide peak late July' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '10.5M acres', notes: 'R2/R3 fungicide mid-July to August' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'EQIP cost-share $25 to $55/acre' },
      { slug: 'wheat', name: 'Wheat', acreage: '600K acres', notes: 'Soft red winter wheat heading June' },
    ],
    rateRange: '$12 to $17',
    neighboringStates: ['iowa', 'indiana', 'missouri', 'wisconsin', 'kentucky'],
    description: 'Illinois is the second-largest corn and soybean state, with $12 to $17 per acre drone spraying rates matching the Iowa benchmark. The state uniquely requires re-testing every 3 years with no continuing education alternative.',
    aeoBlock: 'Illinois ranks second nationally in corn (11M acres) and soybeans (10.5M acres), making it one of the highest-volume drone spray markets in the Corn Belt. Rates run $12 to $17 per acre. The Illinois Department of Agriculture requires an Aerial General Standards exam plus category certification, with mandatory re-testing every 3 years and no CE alternative.',
    faqs: [
      { question: 'What does drone spraying cost in Illinois?', answer: 'Rates run $12 to $17 per acre for corn and soybean applications, matching the Corn Belt baseline. Operator density is high, especially in central and western Illinois, keeping pricing competitive.' },
      { question: 'What license do I need to spray by drone in Illinois?', answer: 'FAA Part 107, Part 137, and an IDA commercial applicator license with Aerial General Standards exam plus at least one category exam. The Aerial GS exam replaces the standard Core exam and is 100 questions at 70% passing.' },
      { question: 'Does Illinois accept continuing education instead of re-testing?', answer: 'No. Illinois is one of the few states with no CE option for aerial applicators. You must pass the Aerial General Standards and category exams again every 3 years to maintain certification.' },
      { question: 'Can I use my Iowa or Indiana license in Illinois?', answer: 'Illinois has reciprocal agreements with IA, IN, MO, WI, and KY. Contact IDA for current reciprocity requirements and any additional exams needed.' },
      { question: 'When is the busiest drone spray season in Illinois?', answer: 'Late July through early August for corn VT/R1 fungicide, overlapping with soybean R2/R3. Cover crop seeding creates a second peak from late August through September. Book 4 to 6 weeks ahead.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    abbreviation: 'IN',
    region: 'corn-belt',
    licensingAgency: 'Office of Indiana State Chemist (OISC) at Purdue University',
    licensingAgencyUrl: 'https://oisc.purdue.edu/pesticide/index.html',
    aerialCategory: 'Category 11: Aerial Application',
    examsRequired: 'Core + Category 11. Exams free at Purdue.',
    examFees: '$45/yr business license + $45/yr applicator license',
    uniqueRules: [
      'OISC exams are administered free of charge at Purdue University.',
      'IPRB Bulletin #143 provides specific drone regulatory guidance.',
      'Indiana participates in DriftWatch sensitive crop registry.',
    ],
    reciprocityStates: ['IL', 'MI', 'OH', 'KY'],
    renewalCycle: '5-year cycle.',
    ceRequirements: '20 CCH (Continuing Certification Hours) per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://oisc.purdue.edu/pesticide/iprb/iprb_143_aerial.pdf',
    extensionUrl: 'https://extension.entm.purdue.edu/fieldcropsipm',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '5.6M acres', notes: 'Tar spot pressure high in recent years' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '5.8M acres', notes: 'Frogeye leaf spot and white mold targets' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Active EQIP participation' },
      { slug: 'wheat', name: 'Wheat', acreage: '450K acres', notes: 'Soft red winter wheat' },
    ],
    rateRange: '$12 to $17',
    neighboringStates: ['illinois', 'ohio', 'michigan', 'kentucky'],
    description: 'Indiana is a core Corn Belt state with strong drone adoption driven by tar spot pressure on corn and Purdue Extension research. Free exams at Purdue make licensing more accessible than most states.',
    aeoBlock: 'Indiana has 5.6 million acres of corn and 5.8 million acres of soybeans, with drone spraying rates of $12 to $17 per acre. The Office of Indiana State Chemist at Purdue administers free licensing exams, and IPRB Bulletin #143 provides specific drone regulatory guidance. Tar spot pressure in recent years has accelerated drone fungicide adoption.',
    faqs: [
      { question: 'What does drone spraying cost in Indiana?', answer: 'Rates run $12 to $17 per acre, consistent with the Corn Belt baseline. High tar spot pressure years push demand and can tighten operator availability in July.' },
      { question: 'What license do I need in Indiana?', answer: 'FAA Part 107, Part 137, and OISC Category 11 (Aerial Application) commercial applicator license. Core and Category 11 exams are free at Purdue University.' },
      { question: 'What is IPRB Bulletin #143?', answer: 'The Indiana Pesticide Review Board published Bulletin #143 specifically addressing drones for pesticide application. It clarifies that Category 11 includes UAS and outlines the layered FAA and state requirements.' },
      { question: 'Does Indiana have reciprocal licensing?', answer: 'Yes, with IL, MI, OH, and KY. Contact OISC for current reciprocity requirements.' },
      { question: 'When is peak drone spray season in Indiana?', answer: 'Late July through early August for corn and soybean fungicide. Tar spot outbreaks can trigger emergency demand in late July. Book by mid-June.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbreviation: 'OH',
    region: 'corn-belt',
    licensingAgency: 'Ohio Department of Agriculture (ODA)',
    licensingAgencyUrl: 'https://agri.ohio.gov/divisions/plant-health/pesticides',
    aerialCategory: 'Category C-1 (commercial license required even for private applicators)',
    examsRequired: 'Core + Category C-1. License $35/yr. Business license $35.',
    examFees: '$35/yr license (exam fee included). Aerial insurance $100K/$300K required.',
    uniqueRules: [
      'Even private applicators must hold a commercial license with Category C-1 to apply any pesticide by drone, including on their own property.',
      'Aerial insurance requirements: $100,000 property damage per occurrence, $100,000 bodily injury per person, $300,000 bodily injury per occurrence.',
      'Certain products prohibited for drone application: Enlist, Acuron (atrazine formulations), Xtend Max (dicamba formulations).',
      'ODA publishes a comprehensive FAQ: "Ohio Requirements for Unmanned Aerial Vehicle Pesticide Applications."',
    ],
    reciprocityStates: ['AL', 'FL', 'GA', 'IL', 'IN', 'LA', 'MI', 'MN'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '5 hours per 3-year cycle (min 1 hr Core, 0.5 hr per category).',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://agri.ohio.gov/divisions/plant-health/pesticides',
    extensionUrl: 'https://cfaes.osu.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '3.4M acres', notes: 'Tar spot expanding west to east' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '4.8M acres', notes: 'Frogeye and white mold in NW Ohio' },
      { slug: 'wheat', name: 'Wheat', acreage: '500K acres', notes: 'Soft red winter wheat, heading early June' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Lake Erie watershed conservation incentives' },
    ],
    rateRange: '$13 to $18',
    neighboringStates: ['indiana', 'michigan', 'kentucky', 'west-virginia'],
    description: 'Ohio has the strictest private applicator rule in the US: even spraying your own land by drone requires a commercial license with Category C-1. Aerial insurance minimums of $100K/$300K are also among the highest.',
    aeoBlock: 'Ohio requires even private applicators to hold a commercial license with Category C-1 for any drone pesticide application, the strictest private applicator rule in the US. Aerial insurance minimums of $100,000 property and $300,000 bodily injury apply. Rates run $13 to $18 per acre across 3.4 million acres of corn and 4.8 million acres of soybeans.',
    faqs: [
      { question: 'Can I spray my own farm by drone with a private applicator license in Ohio?', answer: 'No. Ohio uniquely requires a commercial license with Category C-1 for all drone pesticide applications, even on your own property. A private applicator license is not sufficient.' },
      { question: 'What insurance do I need for drone spraying in Ohio?', answer: '$100,000 property damage per occurrence, $100,000 bodily injury per person, and $300,000 bodily injury per occurrence. These are among the highest state-mandated aerial insurance minimums nationally.' },
      { question: 'Are any pesticides banned for drone application in Ohio?', answer: 'Yes. ODA specifically prohibits drone application of Enlist, Acuron (atrazine formulations), and Xtend Max (dicamba formulations) due to label restrictions and drift concerns.' },
      { question: 'What does drone spraying cost in Ohio?', answer: 'Rates run $13 to $18 per acre, slightly above the Iowa baseline because Ohio has fewer operators and more variable field sizes than western Corn Belt states.' },
      { question: 'Does Ohio have reciprocal licensing?', answer: 'Yes, with AL, FL, GA, IL, IN, LA, MI, MN and others. Contact ODA for current reciprocity requirements.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    abbreviation: 'MO',
    region: 'corn-belt',
    licensingAgency: 'Missouri Department of Agriculture (MDA)',
    licensingAgencyUrl: 'https://agriculture.mo.gov/plants/pesticides',
    aerialCategory: 'Category 13: Aerial Pest Control (commercial/noncommercial). Category 23: Aerial Pest Control (private). Both new as of January 2025.',
    examsRequired: 'Core + Category 13 (or 23) + use categories. $45/exam via Pearson VUE. $65 application fee.',
    examFees: '$45/exam (Pearson VUE). $65 application fee.',
    uniqueRules: [
      'Categories 13 and 23 are new as of January 1, 2025, explicitly including drones.',
      'Provisional applicators (ages 16 to 17) are prohibited from aerial application.',
      'Missouri Bootheel region shares agricultural characteristics with the Mississippi Delta.',
    ],
    reciprocityStates: ['IA', 'IL', 'KS', 'NE', 'AR'],
    renewalCycle: '3-year cycle. Must recertify all categories.',
    ceRequirements: 'Recertification via training or re-exam every 3 years.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.missouri.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '3.3M acres', notes: 'Northern Missouri corn belt' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '5.7M acres', notes: '#1 crop by acreage' },
      { slug: 'rice', name: 'Rice', acreage: '200K acres', notes: 'Bootheel region' },
      { slug: 'cotton', name: 'Cotton', acreage: '300K acres', notes: 'Bootheel region' },
    ],
    rateRange: '$12 to $18',
    neighboringStates: ['iowa', 'illinois', 'kansas', 'arkansas', 'kentucky', 'tennessee'],
    description: 'Missouri introduced new aerial drone categories (13 and 23) in January 2025. The state spans two agricultural worlds: Corn Belt row crops in the north and Delta-style rice and cotton in the Bootheel.',
    aeoBlock: 'Missouri introduced Category 13 (commercial) and Category 23 (private) Aerial Pest Control licensing effective January 2025, explicitly including drones. The state covers 5.7 million acres of soybeans and 3.3 million acres of corn in northern Missouri, plus rice and cotton in the Bootheel. Rates run $12 to $18 per acre.',
    faqs: [
      { question: 'What changed in Missouri drone licensing in 2025?', answer: 'Missouri introduced Category 13 (Aerial Pest Control, commercial/noncommercial) and Category 23 (Aerial Pest Control, private) effective January 1, 2025. Both explicitly include drone operations. Previously there was no drone-specific aerial category.' },
      { question: 'What does drone spraying cost in Missouri?', answer: 'Northern Missouri row crops run $12 to $17 per acre. Bootheel rice and cotton run $14 to $18. The split reflects the two distinct agricultural regions within the state.' },
      { question: 'Can minors apply for Missouri aerial applicator licensing?', answer: 'No. Provisional applicators (ages 16 to 17) are explicitly prohibited from aerial application under the new Category 13/23 rules.' },
      { question: 'Does Missouri have reciprocal licensing?', answer: 'Yes, with IA, IL, KS, NE, AR and potentially others. Contact MDA for current reciprocity list.' },
      { question: 'What crops drive drone demand in the Missouri Bootheel?', answer: 'Rice (200K acres) and cotton (300K acres) in the Bootheel share characteristics with the Mississippi Delta. Flooded rice paddies and soft fall soils make drones essential for heading-stage fungicide and cotton defoliant.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbreviation: 'MI',
    region: 'corn-belt',
    licensingAgency: 'Michigan Department of Agriculture and Rural Development (MDARD)',
    licensingAgencyUrl: 'https://www.michigan.gov/mdard/licensing/pesticide/aerial-pesticide-applications',
    aerialCategory: 'AE (Aerial Standard) + Core + use categories',
    examsRequired: 'Core + AE (Aerial Standard) + use categories. 70% passing. 3 years/200 hours flight experience or MDARD-approved UAV training program.',
    examFees: 'Contact MDARD for current fees.',
    uniqueRules: [
      'MDARD-approved UAV training program required (de facto drone-specific credential).',
      'Mix/Load pad in Michigan required for aerial operations.',
      'Private Aerial Business License (PABL) required.',
      'DriftWatch sensitive crop registry participation required.',
      'Reciprocity with IN, MN, OH, WI includes drone-specific training submission requirement.',
    ],
    reciprocityStates: ['IN', 'MN', 'OH', 'WI'],
    renewalCycle: '3-year cycle. Flight efficiency clinic or re-test.',
    ceRequirements: 'Flight efficiency clinic or re-examination every 3 years.',
    droneSpecificCredential: true,
    droneGuidanceUrl: 'https://www.michigan.gov/mdard/licensing/pesticide/aerial-pesticide-applications',
    extensionUrl: 'https://www.canr.msu.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '2.2M acres', notes: 'Western Michigan concentration' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '2.1M acres', notes: 'Growing drone adoption' },
      { slug: 'orchards', name: 'Cherries/Apples', acreage: '100K acres', notes: 'Traverse City tart cherry, west MI apples' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Great Lakes watershed incentives' },
    ],
    rateRange: '$14 to $22',
    neighboringStates: ['indiana', 'ohio', 'wisconsin', 'minnesota'],
    description: 'Michigan is one of the few states with a de facto drone-specific credential: MDARD requires an approved UAV training program before issuing aerial certification. Tart cherry and apple orchards in western Michigan add specialty crop demand.',
    aeoBlock: 'Michigan requires a MDARD-approved UAV training program as a de facto drone-specific credential, plus Core and Aerial Standard (AE) exams and a Private Aerial Business License (PABL). Rates run $14 to $22 per acre across 2.2 million acres of corn, 2.1 million acres of soybeans, and high-value tart cherry and apple orchards in western Michigan.',
    faqs: [
      { question: 'Does Michigan require drone-specific training?', answer: 'Yes. MDARD requires completion of an approved UAV training program before issuing the AE (Aerial Standard) certification. This is one of the few states with a de facto drone-specific credential requirement.' },
      { question: 'What is the PABL requirement?', answer: 'A Private Aerial Business License (PABL) is required for all aerial pesticide application businesses in Michigan, including drone operators. This is in addition to individual applicator certification.' },
      { question: 'What does drone spraying cost in Michigan?', answer: 'Row crops run $14 to $18 per acre. Cherry and apple orchard work runs $18 to $22 because of canopy complexity and multiple passes. Western Michigan orchards command the highest rates.' },
      { question: 'Can I use my Indiana or Ohio license in Michigan?', answer: 'Michigan has reciprocity with IN, MN, OH, and WI, but reciprocal applicants must still submit drone-specific training documentation to MDARD.' },
      { question: 'What is DriftWatch and do I need it?', answer: 'DriftWatch is a voluntary sensitive crop registry. Michigan requires aerial applicators to check DriftWatch before spraying to identify specialty crop fields (vineyards, orchards, organic) near the application zone.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    abbreviation: 'WI',
    region: 'corn-belt',
    licensingAgency: 'Wisconsin DATCP',
    licensingAgencyUrl: 'https://datcp.wi.gov',
    aerialCategory: 'Category 9.9: Aerial Applicator (supplementary certification under ATCP 29.28)',
    examsRequired: 'Core + Category 9.9 + use categories.',
    examFees: 'Contact DATCP for current fees.',
    uniqueRules: [
      'Category 9.9 explicitly covers "airplanes, helicopters, or unmanned aircraft systems (drones)."',
      'Supplementary certification, not standalone.',
    ],
    reciprocityStates: ['IA', 'IL', 'MI', 'MN'],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'CE hours vary by category per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.wisc.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '3.9M acres', notes: 'Tar spot expanding into southern WI' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '1.9M acres', notes: 'White mold in northern counties' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Fox-Wolf Watershed drone seeding programs' },
    ],
    rateRange: '$13 to $18',
    neighboringStates: ['iowa', 'illinois', 'michigan', 'minnesota'],
    description: 'Wisconsin Category 9.9 explicitly includes drones alongside airplanes and helicopters. Cover crop drone seeding is growing fast, with the Fox-Wolf Watershed Alliance running pilot programs at $20 per acre.',
    aeoBlock: 'Wisconsin uses Category 9.9 (Aerial Applicator) which explicitly covers drones alongside airplanes and helicopters. Rates run $13 to $18 per acre across 3.9 million acres of corn and 1.9 million acres of soybeans. Cover crop drone seeding is expanding, with the Fox-Wolf Watershed Alliance running programs at $20 per acre.',
    faqs: [
      { question: 'What aerial category covers drones in Wisconsin?', answer: 'Category 9.9 (Aerial Applicator) under ATCP 29.28. It explicitly covers airplanes, helicopters, and unmanned aircraft systems (drones) as a supplementary certification.' },
      { question: 'What does drone spraying cost in Wisconsin?', answer: 'Row crop rates run $13 to $18 per acre. Cover crop seeding runs $18 to $20. Slightly higher than Iowa due to fewer operators and more variable terrain in western and northern counties.' },
      { question: 'Is cover crop drone seeding popular in Wisconsin?', answer: 'Yes and growing. The Fox-Wolf Watershed Alliance has run pilot drone seeding programs, and NRCS EQIP cost-share makes it economically attractive across the state.' },
      { question: 'Does Wisconsin have reciprocal licensing?', answer: 'Yes, with IA, IL, MI, and MN. Contact DATCP for current reciprocity procedures.' },
      { question: 'When is peak drone spray season in Wisconsin?', answer: 'Late July through early August for corn and soybean fungicide. Wisconsin sits 1 to 2 weeks behind Iowa in timing due to northern latitude. Cover crop seeding runs September through early October.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbreviation: 'MN',
    region: 'corn-belt',
    licensingAgency: 'Minnesota Department of Agriculture (MDA)',
    licensingAgencyUrl: 'https://www.mda.state.mn.us',
    aerialCategory: 'Category B: General Aerial. Plus MnDOT aircraft registration and commercial operations license.',
    examsRequired: 'Category A + Category B + site category. 70% passing. $5 endorsement (private).',
    examFees: '$5 private endorsement. Commercial fees contact MDA.',
    uniqueRules: [
      'MnDOT aircraft registration required for all drones used in aerial application.',
      'MnDOT commercial operations license with insurance required.',
      'Aerial endorsement (private) vs full Category B (commercial) distinction.',
      'Minnesota has reciprocity with 18 states, the most extensive reciprocal network in the US.',
    ],
    reciprocityStates: ['ND', 'SD', 'IA', 'WI', 'AR', 'IL', 'IN', 'KS', 'LA', 'MI', 'MS', 'MO', 'MT', 'NE', 'OH', 'OK', 'TX', 'WY'],
    renewalCycle: 'Annual recertification for Category B (commercial). 3-year cycle (private).',
    ceRequirements: 'Annual recertification meeting or re-exam for commercial aerial.',
    droneSpecificCredential: true,
    droneGuidanceUrl: 'https://www.mda.state.mn.us',
    extensionUrl: 'https://extension.umn.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '8.1M acres', notes: 'Second only to Iowa in the Corn Belt' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '7.4M acres', notes: 'Soybean aphid and white mold pressure' },
      { slug: 'wheat', name: 'Wheat', acreage: '1.2M acres', notes: 'Spring wheat in northwest MN' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'EQIP participation expanding' },
    ],
    rateRange: '$12 to $17',
    neighboringStates: ['iowa', 'wisconsin', 'north-dakota', 'south-dakota'],
    description: 'Minnesota has the most extensive reciprocal licensing network in the US (18 states) and requires both MDA Category B certification and MnDOT aircraft registration. 8.1 million acres of corn make it the second-largest Corn Belt market.',
    aeoBlock: 'Minnesota requires Category B (General Aerial) certification plus MnDOT aircraft registration and commercial operations license. The state has reciprocity with 18 states, the most extensive network nationally. Rates run $12 to $17 per acre across 8.1 million acres of corn and 7.4 million acres of soybeans.',
    faqs: [
      { question: 'What makes Minnesota licensing unique?', answer: 'Two things: MnDOT aircraft registration is required for all drones (separate from FAA), and Minnesota has the broadest reciprocal licensing network in the US at 18 states.' },
      { question: 'What does drone spraying cost in Minnesota?', answer: 'Rates run $12 to $17 per acre for row crops. Spring wheat in northwest Minnesota adds a May/June heading window separate from the July corn/soybean peak.' },
      { question: 'Do I need to register my drone with MnDOT?', answer: 'Yes. MnDOT requires aircraft registration for all drones used in commercial operations, including aerial pesticide application. This is in addition to FAA registration. A MnDOT commercial operations license with insurance is also required.' },
      { question: 'What is the difference between private endorsement and Category B?', answer: 'Private aerial endorsement ($5) allows farmers to spray their own land. Category B (General Aerial) is the full commercial certification for operators spraying land they do not own. Commercial operators need annual recertification.' },
      { question: 'When is peak spray season in Minnesota?', answer: 'Corn VT/R1 in late July to early August. Soybean R2/R3 overlaps. Spring wheat heading in late June to early July in northwest MN. Cover crop seeding September through early October.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    abbreviation: 'KY',
    region: 'corn-belt',
    licensingAgency: 'Kentucky Department of Agriculture (KDA)',
    licensingAgencyUrl: 'https://www.kyagr.com/consumer/obtaining-certification.html',
    aerialCategory: 'Category 11: Aerial Certification (explicitly includes UAS)',
    examsRequired: 'Core + Category 11 + site category (minimum 3 exams). $10/exam. $25 license.',
    examFees: '$10/exam. $25 license fee.',
    uniqueRules: [
      'Category 11 is not standalone; must pair with at least one site category.',
      'Even general-use pesticides require certification when applied aerially.',
      'Kentucky is at the southern edge of the Corn Belt with a mixed crop profile.',
    ],
    reciprocityStates: ['IL', 'IN', 'OH', 'TN', 'VA', 'WV'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '12 hours per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.uky.edu/ccd',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '1.4M acres', notes: 'Central Kentucky' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '1.7M acres', notes: 'Western Kentucky concentration' },
      { slug: 'wheat', name: 'Wheat', acreage: '400K acres', notes: 'Soft red winter wheat' },
    ],
    rateRange: '$14 to $19',
    neighboringStates: ['indiana', 'ohio', 'tennessee', 'west-virginia', 'virginia', 'missouri', 'illinois'],
    description: 'Kentucky sits at the southern edge of the Corn Belt with rates of $14 to $19 per acre. Category 11 explicitly includes UAS, and even general-use pesticides require certification when applied aerially.',
    aeoBlock: 'Kentucky Category 11 (Aerial Certification) explicitly includes UAS and requires pairing with a site category, making a minimum of 3 exams. Even general-use pesticides require aerial certification when applied by drone. Rates run $14 to $19 per acre across 1.7 million acres of soybeans and 1.4 million acres of corn.',
    faqs: [
      { question: 'What does drone spraying cost in Kentucky?', answer: 'Rates run $14 to $19 per acre, slightly above the core Corn Belt baseline due to fewer operators and more variable terrain. Western Kentucky is flatter and more competitive.' },
      { question: 'Do general-use pesticides require certification for drone application in Kentucky?', answer: 'Yes. Kentucky requires aerial certification for all pesticides applied by aircraft, including drones, regardless of whether the product is general-use or restricted-use. This catches some operators by surprise.' },
      { question: 'Can I get Category 11 alone in Kentucky?', answer: 'No. Category 11 is not standalone. You must pair it with at least one site category (e.g., agricultural pest control), making the minimum 3 exams: Core, Category 11, and a site category.' },
      { question: 'Does Kentucky have reciprocal licensing?', answer: 'Yes, with IL, IN, OH, TN, VA, and WV. Contact KDA for current procedures.' },
      { question: 'What crops drive drone demand in Kentucky?', answer: 'Soybeans (1.7M acres) and corn (1.4M acres) are the primary markets. Soft red winter wheat adds a late May/June heading window. Tobacco in central Kentucky is a niche specialty crop opportunity.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    abbreviation: 'TN',
    region: 'corn-belt',
    licensingAgency: 'Tennessee Department of Agriculture (TDA)',
    licensingAgencyUrl: 'https://psep.tennessee.edu/aerial-applicator-license',
    aerialCategory: 'AER (Aerial) licensing exam + category certification',
    examsRequired: 'Core + category certification + AER licensing exam. Exam application $150. AER exam $15. Pilot fee $200.',
    examFees: '$150 exam application. $15 AER exam. $200 pilot fee. $150 per aircraft decal. $100K insurance required.',
    uniqueRules: [
      'Each drone must carry a TDA aircraft decal at $150 each.',
      '$100,000 minimum liability insurance required.',
      'FAA Part 137 required and must be on file with TDA.',
      'Three separate fees: exam application, AER exam, and pilot fee.',
    ],
    reciprocityStates: ['AL', 'AR', 'GA', 'KY', 'LA', 'MS', 'MO', 'NC', 'SC'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '18 points per 3-year cycle (Agriculture C01). Distribution and format restrictions apply.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://psep.tennessee.edu/pesticide-application-using-drones',
    extensionUrl: 'https://extension.tennessee.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '800K acres', notes: 'West Tennessee' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '1.5M acres', notes: '#1 crop' },
      { slug: 'cotton', name: 'Cotton', acreage: '500K acres', notes: 'West Tennessee Delta region' },
      { slug: 'wheat', name: 'Wheat', acreage: '300K acres', notes: 'Soft red winter wheat' },
    ],
    rateRange: '$14 to $20',
    neighboringStates: ['kentucky', 'virginia', 'north-carolina', 'georgia', 'alabama', 'mississippi', 'arkansas', 'missouri'],
    description: 'Tennessee has the highest per-drone entry cost in the Corn Belt: $150 aircraft decal per drone, $200 pilot fee, $150 exam application, plus $100K insurance. West Tennessee shares Delta agricultural characteristics with cotton and rice.',
    aeoBlock: 'Tennessee requires a $150 aircraft decal per drone, $200 pilot fee, and $100,000 minimum liability insurance, making it the highest per-drone entry cost in the Corn Belt region. West Tennessee grows 500,000 acres of cotton and 1.5 million acres of soybeans. Rates run $14 to $20 per acre.',
    faqs: [
      { question: 'What does it cost to get licensed for drone spraying in Tennessee?', answer: '$150 exam application, $15 AER exam fee, $200 pilot fee, and $150 per aircraft decal. Each drone in your fleet needs its own $150 decal. Add $100K minimum liability insurance. Total entry cost for a single-drone operator is approximately $615 before insurance.' },
      { question: 'What does drone spraying cost in Tennessee?', answer: 'Rates run $14 to $20 per acre. West Tennessee (Delta-influenced) runs slightly higher due to cotton defoliant complexity. East Tennessee mountainous terrain adds difficulty for some operations.' },
      { question: 'Does each drone need a separate TDA decal?', answer: 'Yes. Each drone must carry its own TDA aircraft decal at $150 per decal. Multi-drone fleet operators should factor this into their annual fixed costs.' },
      { question: 'Does Tennessee have reciprocal licensing?', answer: 'Yes, with AL, AR, GA, KY, LA, MS, MO, NC, and SC. Reciprocity covers certification only, not licensing. You still need TDA pilot fees and aircraft decals.' },
      { question: 'What crops drive drone demand in Tennessee?', answer: 'Soybeans (1.5M acres) statewide, cotton (500K acres) in west Tennessee, corn (800K acres), and wheat (300K). West Tennessee shares Delta-style agriculture with Mississippi and Arkansas.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
