// GREAT PLAINS BATCH: Add these 9 state objects to states array.
// Texas already exists. Append these.

  {
    slug: 'kansas',
    name: 'Kansas',
    abbreviation: 'KS',
    region: 'great-plains',
    licensingAgency: 'Kansas Department of Agriculture (KDA)',
    licensingAgencyUrl: 'https://www.agriculture.ks.gov/divisions-programs/pesticide-and-fertilizer/pesticide-applicator',
    aerialCategory: 'No single aerial category. Use-specific categories (1A/1B/1C/1D, 2, 3A/3B, 5, 6, 7C/7D, 10)',
    examsRequired: 'General Standards + category exams. $45/exam. $50/category recertification.',
    examFees: '$45/exam. $50/category recert.',
    uniqueRules: [
      'No standalone aerial exam. Instead, must submit a separate UAS Application to the Secretary of Agriculture for approval before any drone pesticide application.',
      'UAS Application must include FAA registration certificate, Remote Pilot Certificate, drone make/model/serial, and Part 137 documentation.',
      'Only certified commercial applicators may apply pesticides via UAS. Registered pest control technicians and uncertified applicators are ineligible.',
      'UAS policy implemented July 2022, expanded January 2023, revised April 7, 2025.',
    ],
    reciprocityStates: ['IN', 'MN', 'MO', 'NE', 'OK', 'TX'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '1 core + 3 to 7 pest management hours per 3-year cycle (varies by category).',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://www.agriculture.ks.gov/divisions-programs/pesticide-and-fertilizer/unmanned-aircraft-systems',
    extensionUrl: 'https://www.ksre.k-state.edu',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '7.5M acres', notes: '#1 wheat state. Heading late May to early June.' },
      { slug: 'corn', name: 'Corn', acreage: '5.5M acres', notes: 'Eastern and irrigated western KS' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '4.5M acres', notes: 'Eastern Kansas' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'EQIP participation expanding' },
    ],
    rateRange: '$12 to $16',
    neighboringStates: ['nebraska', 'oklahoma', 'colorado', 'missouri'],
    description: 'Kansas is the #1 wheat state in the US at 7.5 million acres. Drone operators must submit a separate UAS Application to the Secretary of Agriculture for approval, a unique pre-authorization step beyond standard licensing.',
    aeoBlock: 'Kansas is the top US wheat state at 7.5 million acres, with drone spraying rates of $12 to $16 per acre. KDA requires a separate UAS Application approved by the Secretary of Agriculture before any drone pesticide application, in addition to standard commercial applicator certification. The wheat heading window in late May to early June is the primary drone spray demand driver.',
    faqs: [
      { question: 'What is the Kansas UAS Application?', answer: 'A separate application submitted to the Kansas Secretary of Agriculture that includes your FAA registration, Part 107, Part 137, and drone make/model/serial. You cannot spray by drone in Kansas without this pre-approval, even if you hold all other licenses.' },
      { question: 'What does drone spraying cost in Kansas?', answer: 'Wheat and row crop applications run $12 to $16 per acre. Large flat acreage pushes rates toward the low end. Wind conditions often limit daily spray windows.' },
      { question: 'When is the wheat spray window in Kansas?', answer: 'T3 heading arrives in late May to early June, with a 5 to 7 day window. Book in April. Operators who wait until heading is visible often cannot find available capacity.' },
      { question: 'Can a pest control technician spray by drone in Kansas?', answer: 'No. KDA explicitly limits drone pesticide application to certified commercial applicators only. Registered pest control technicians and uncertified applicators are ineligible.' },
      { question: 'Does Kansas have reciprocal licensing?', answer: 'Yes, with IN, MN, MO, NE, OK, and TX. The UAS Application is still required regardless of reciprocity.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    abbreviation: 'NE',
    region: 'great-plains',
    licensingAgency: 'Nebraska Department of Agriculture (NDA)',
    licensingAgencyUrl: 'https://nda.nebraska.gov/pesticide/aerial_license',
    aerialCategory: 'Category 12: Aerial Pest Control',
    examsRequired: 'General Standards + Category 12. $55/exam via Pearson VUE. License $90/3yr.',
    examFees: '$55/exam (Pearson VUE). $90 license for 3 years.',
    uniqueRules: [
      'NDA classifies ALL drone pesticide application as aerial, regardless of drone size.',
      'Nebraska Aerial Pesticide Business License required.',
      'NE PSC Precision Ag Grant Program funds drone acquisition for farmers.',
    ],
    reciprocityStates: ['WY', 'WA', 'ND', 'TX', 'SD', 'MT', 'MO', 'KS', 'MN', 'MS'],
    renewalCycle: '3-year cycle. Recertification training or re-exam.',
    ceRequirements: 'Recertification training or re-exam every 3 years.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://nda.nebraska.gov/pesticide/aerial_license',
    extensionUrl: 'https://extension.unl.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '9.8M acres', notes: '#3 corn state nationally' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '5.4M acres', notes: 'Eastern Nebraska' },
      { slug: 'wheat', name: 'Wheat', acreage: '1.1M acres', notes: 'Winter wheat in western NE' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Precision Ag Grant funding available' },
    ],
    rateRange: '$12 to $16',
    neighboringStates: ['iowa', 'kansas', 'south-dakota', 'colorado', 'wyoming'],
    description: 'Nebraska classifies all drone pesticide application as aerial regardless of size and offers a state Precision Ag Grant Program that funds drone acquisition for farmers. 9.8 million acres of corn make it the #3 corn state.',
    aeoBlock: 'Nebraska classifies all drone pesticide application as aerial regardless of drone size, requiring Category 12 (Aerial Pest Control) and an Aerial Pesticide Business License. The NE PSC Precision Ag Grant Program provides funding for drone acquisition. Rates run $12 to $16 per acre across 9.8 million acres of corn.',
    faqs: [
      { question: 'Does Nebraska treat small drones differently from large ones?', answer: 'No. NDA classifies all drone pesticide application as aerial regardless of size. Even a sub-55-lb drone applying pesticide requires Category 12 and an Aerial Pesticide Business License.' },
      { question: 'What is the Nebraska Precision Ag Grant Program?', answer: 'The NE Public Service Commission offers grants to fund precision agriculture equipment including drones for farmers. This can offset purchase costs separately from USDA EQIP.' },
      { question: 'What does drone spraying cost in Nebraska?', answer: '$12 to $16 per acre for row crops. Large irrigated fields in central and western Nebraska get the lowest rates. Eastern Nebraska pricing is competitive with Iowa.' },
      { question: 'Does Nebraska have reciprocal licensing?', answer: 'Yes, with WY, WA, ND, TX, SD, MT, MO, KS, MN, and MS. One of the broader reciprocity lists in the Great Plains.' },
      { question: 'When is peak spray season in Nebraska?', answer: 'Corn VT/R1 in late July. Wheat heading in early June in western NE. Cover crop seeding August through October.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'north-dakota',
    name: 'North Dakota',
    abbreviation: 'ND',
    region: 'great-plains',
    licensingAgency: 'ND Aeronautics Commission + NDSU Extension',
    licensingAgencyUrl: 'https://aero.nd.gov',
    aerialCategory: 'Unmanned Aerial Applicator License (separate from manned aerial)',
    examsRequired: 'Core Aerial exam + category exam via NDSU. Then separate Aeronautics Commission license.',
    examFees: '~$10 exam + $25 NDSU certification + $200 Aeronautics license.',
    uniqueRules: [
      'Only state with a formally separate Unmanned Aerial Applicator License issued by the Aeronautics Commission.',
      'All unmanned aircraft must be registered with the ND Aeronautics Commission before use.',
      'Applicators must report acreage to the Commission by December 1 annually.',
      'As of 2024, only 21 licensed unmanned aerial applicators operated in North Dakota.',
      'PAASS (Professional Aerial Applicators Support System) safety meeting attendance required.',
    ],
    reciprocityStates: ['SD', 'MN', 'MT'],
    renewalCycle: '3-year cycle via recertification training or re-exam.',
    ceRequirements: 'PAASS attendance required. Recertification every 3 years.',
    droneSpecificCredential: true,
    droneGuidanceUrl: 'https://aero.nd.gov',
    extensionUrl: 'https://www.ndsu.edu/agriculture',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '6.5M acres', notes: 'Hard red spring wheat. Heading late June to early July.' },
      { slug: 'corn', name: 'Corn', acreage: '3.5M acres', notes: 'Southeastern ND' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '5.8M acres', notes: '#2 soybean state after IA' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Short season limits establishment' },
    ],
    rateRange: '$12 to $17',
    neighboringStates: ['south-dakota', 'minnesota', 'montana'],
    description: 'North Dakota is the only state with a formally separate Unmanned Aerial Applicator License issued by the Aeronautics Commission. Only 21 licensed operators as of 2024 across 6.5 million acres of wheat and 5.8 million acres of soybeans.',
    aeoBlock: 'North Dakota is the only US state with a formally separate Unmanned Aerial Applicator License, issued by the ND Aeronautics Commission ($200) in addition to NDSU pesticide certification. As of 2024, only 21 licensed unmanned aerial applicators served the state 6.5 million acres of wheat and 5.8 million acres of soybeans. Rates run $12 to $17 per acre.',
    faqs: [
      { question: 'What makes North Dakota drone licensing unique?', answer: 'ND is the only state with a separate Unmanned Aerial Applicator License issued by the Aeronautics Commission. This is distinct from the manned aerial applicator license and requires separate NDSU certification plus Commission registration.' },
      { question: 'How many drone operators are in North Dakota?', answer: 'As of 2024, only 21 licensed unmanned aerial applicators with 46 pilots and 37 aircraft treated 69,032 acres. This is a severely underserved market relative to acreage.' },
      { question: 'What does drone spraying cost in North Dakota?', answer: '$12 to $17 per acre. Spring wheat heading in late June to early July is the peak window. Low operator density means less pricing pressure than Iowa or Illinois.' },
      { question: 'Do I need to report acreage in North Dakota?', answer: 'Yes. All unmanned aerial applicators must report acreage treated to the ND Aeronautics Commission by December 1 annually.' },
      { question: 'When does spring wheat heading hit in North Dakota?', answer: 'Late June to early July. The window is 5 to 7 days. Book in April or early May. With only 21 licensed operators statewide, capacity fills fast.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'south-dakota',
    name: 'South Dakota',
    abbreviation: 'SD',
    region: 'great-plains',
    licensingAgency: 'South Dakota DANR',
    licensingAgencyUrl: 'https://danr.sd.gov/Agriculture/Inspection/Pesticide/ApplicatorsDealers/default.aspx',
    aerialCategory: 'Category 17: Aerial Application (General + Category G + Category 17)',
    examsRequired: 'Core Category G + Category 17 + 1 use category. License $35/2yr.',
    examFees: '$35 license for 2 years.',
    uniqueRules: [
      'Class 3 Medical certificate may be required.',
      'Remote ID compliance required since September 2023.',
      'SDSU Extension publishes a detailed drone pesticide application guide (P-00354).',
    ],
    reciprocityStates: ['MT', 'ND', 'MN', 'IA', 'NE', 'WY'],
    renewalCycle: '2-year cycle via recertification classes or online course.',
    ceRequirements: 'Recertification every 2 years via classes or online.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://extension.sdstate.edu/sites/default/files/2025-09/P-00354-v2.pdf',
    extensionUrl: 'https://extension.sdstate.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '5.6M acres', notes: 'Eastern SD' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '5.1M acres', notes: 'Strong growth area' },
      { slug: 'wheat', name: 'Wheat', acreage: '2.2M acres', notes: 'Spring and winter wheat' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'EQIP participation' },
    ],
    rateRange: '$12 to $16',
    neighboringStates: ['north-dakota', 'minnesota', 'iowa', 'nebraska', 'wyoming', 'montana'],
    description: 'South Dakota has one of the lowest licensing fee structures in the Great Plains at $35 for 2 years. SDSU Extension publishes a comprehensive drone pesticide application guide.',
    aeoBlock: 'South Dakota requires Category 17 (Aerial Application) with a $35 license fee for 2 years, one of the lowest cost structures in the region. SDSU Extension publishes a comprehensive drone guide (P-00354). Rates run $12 to $16 per acre across 5.6 million acres of corn and 5.1 million acres of soybeans.',
    faqs: [
      { question: 'What does drone spraying cost in South Dakota?', answer: '$12 to $16 per acre for row crops. Eastern SD (corn/soybean) is competitive with Iowa pricing. Western SD wheat fields are larger with slightly lower rates.' },
      { question: 'What license do I need in South Dakota?', answer: 'FAA Part 107, Part 137, and DANR commercial applicator license with Category G (General) + Category 17 (Aerial Application) + at least one use category. License is $35 for 2 years.' },
      { question: 'Is there a drone-specific guide for South Dakota?', answer: 'Yes. SDSU Extension publishes P-00354 "Drone Pesticide Application Guide" (updated September 2025), covering all state and federal requirements in one document.' },
      { question: 'Does South Dakota require Remote ID?', answer: 'Yes, since September 2023 for all commercial UAS operations, consistent with the FAA Remote ID rule.' },
      { question: 'Does South Dakota have reciprocal licensing?', answer: 'Yes, with MT, ND, MN, IA, NE, and WY.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'montana',
    name: 'Montana',
    abbreviation: 'MT',
    region: 'great-plains',
    licensingAgency: 'Montana Department of Agriculture (MDA)',
    licensingAgencyUrl: 'https://agr.mt.gov',
    aerialCategory: 'Category 18: Aerial Applicator',
    examsRequired: 'Core + Category 18 + 1 use-site category (3 exams). Exams free at MDA field offices. License $85/yr.',
    examFees: 'Exams free at MDA field offices. License $85/yr.',
    uniqueRules: [
      'Exams are free at MDA field offices, unusual nationally.',
      'Large ranch acreage creates demand for pasture and rangeland drone applications.',
    ],
    reciprocityStates: ['ND', 'SD', 'WY', 'NE'],
    renewalCycle: '5-year cycle.',
    ceRequirements: '12 credits per category per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.montana.edu/extension',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '5.2M acres', notes: 'Spring and winter wheat. #2 wheat state.' },
      { slug: 'corn', name: 'Corn', acreage: '200K acres', notes: 'Limited, eastern MT only' },
    ],
    rateRange: '$12 to $18',
    neighboringStates: ['north-dakota', 'south-dakota', 'wyoming', 'idaho'],
    description: 'Montana is the #2 wheat state at 5.2 million acres with free licensing exams at MDA field offices. Large ranch operations add pasture and rangeland drone demand.',
    aeoBlock: 'Montana is the #2 US wheat state at 5.2 million acres, with Category 18 (Aerial Applicator) licensing and free exams at MDA field offices. Rates run $12 to $18 per acre. Large ranch acreage creates additional demand for pasture and rangeland drone applications beyond row crop spraying.',
    faqs: [
      { question: 'What does drone spraying cost in Montana?', answer: 'Wheat applications run $12 to $16 per acre. Pasture and rangeland work runs $15 to $18 due to remote field access and travel distances.' },
      { question: 'Are Montana licensing exams really free?', answer: 'Yes. MDA administers exams at field offices at no charge, which is unusual nationally. The license itself is $85 per year.' },
      { question: 'When is wheat heading in Montana?', answer: 'Winter wheat heads in late May to early June. Spring wheat heads in late June to early July, overlapping with North Dakota timing.' },
      { question: 'Is there drone demand beyond wheat in Montana?', answer: 'Yes. Pasture and rangeland applications (brush control, spot herbicide treatment) on large ranch operations are an emerging niche. Drones access remote terrain that ground rigs cannot reach efficiently.' },
      { question: 'Does Montana have reciprocal licensing?', answer: 'Yes, with ND, SD, WY, and NE. Must pass MT rules exam.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'wyoming',
    name: 'Wyoming',
    abbreviation: 'WY',
    region: 'great-plains',
    licensingAgency: 'Wyoming Department of Agriculture',
    licensingAgencyUrl: 'https://agriculture.wy.gov',
    aerialCategory: 'Aerial Application (WY Admin Code Ch. 28, Sec. 28-5, explicitly includes UAS)',
    examsRequired: 'Core + Aerial + use category.',
    examFees: 'Contact WDA for current fees.',
    uniqueRules: [
      'Aerial application category explicitly includes UAS in the administrative code.',
      'Smallest agricultural state in the Great Plains by crop acreage.',
    ],
    reciprocityStates: ['MT', 'NE', 'SD', 'CO'],
    renewalCycle: '3-year cycle.',
    ceRequirements: 'Contact WDA for current CE requirements.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.uwyo.edu/uwe',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '300K acres', notes: 'Limited acreage' },
    ],
    rateRange: '$14 to $20',
    neighboringStates: ['montana', 'south-dakota', 'nebraska', 'colorado'],
    description: 'Wyoming has the smallest agricultural crop acreage in the Great Plains but explicit UAS inclusion in its aerial application code. Ranch and rangeland applications are the primary drone opportunity.',
    aeoBlock: 'Wyoming explicitly includes UAS in its aerial application administrative code (Ch. 28, Sec. 28-5). Agricultural crop acreage is the smallest in the Great Plains, but ranch and rangeland applications create niche drone demand. Rates run $14 to $20 per acre.',
    faqs: [
      { question: 'Is there much drone spray demand in Wyoming?', answer: 'Limited for row crops. Primary demand is rangeland and pasture applications on large ranch operations, plus some wheat and sugar beet work. Rates are higher due to remote locations and travel distances.' },
      { question: 'Does Wyoming aerial licensing explicitly cover drones?', answer: 'Yes. WY Admin Code Chapter 28, Section 28-5 explicitly includes UAS in the aerial application definition.' },
      { question: 'What does drone spraying cost in Wyoming?', answer: '$14 to $20 per acre. Higher than neighboring states due to small fields, remote locations, and few operators.' },
      { question: 'Does Wyoming have reciprocal licensing?', answer: 'Yes, with MT, NE, SD, and CO.' },
      { question: 'What crops drive drone demand in Wyoming?', answer: 'Wheat (300K acres), sugar beets in the Big Horn Basin, and alfalfa hay. Rangeland brush control and spot herbicide treatment on cattle ranches are growing applications.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbreviation: 'CO',
    region: 'great-plains',
    licensingAgency: 'Colorado Department of Agriculture (CDA)',
    licensingAgencyUrl: 'https://ag.colorado.gov',
    aerialCategory: 'Category 114: Aerial Pest Control (explicitly includes UAV)',
    examsRequired: 'Core + Category 114 + site category. $41.50/exam. $350/yr business license.',
    examFees: '$41.50/exam. $350/yr business license.',
    uniqueRules: [
      'Category 114 explicitly includes UAV.',
      'Business license at $350/yr is among the higher state fees.',
    ],
    reciprocityStates: ['NE', 'WY', 'NM'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '7 core + 1 per category per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.colostate.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '1.3M acres', notes: 'Eastern CO irrigated' },
      { slug: 'wheat', name: 'Wheat', acreage: '2.2M acres', notes: 'Eastern plains winter wheat' },
    ],
    rateRange: '$13 to $18',
    neighboringStates: ['nebraska', 'kansas', 'wyoming', 'new-mexico', 'oklahoma'],
    description: 'Colorado Category 114 (Aerial Pest Control) explicitly includes UAV. The $350/yr business license is among the higher state fees. Eastern plains wheat and irrigated corn drive the primary demand.',
    aeoBlock: 'Colorado uses Category 114 (Aerial Pest Control) which explicitly includes UAV, with a $350 per year business license among the higher state fees nationally. Rates run $13 to $18 per acre across 2.2 million acres of wheat and 1.3 million acres of irrigated corn on the eastern plains.',
    faqs: [
      { question: 'Does Colorado aerial licensing cover drones?', answer: 'Yes. Category 114 (Aerial Pest Control) explicitly includes UAV. No separate drone credential needed beyond the standard aerial category.' },
      { question: 'What does drone spraying cost in Colorado?', answer: '$13 to $18 per acre. Eastern plains wheat and corn get competitive rates. Mountain and western slope applications are higher due to terrain and travel.' },
      { question: 'Is the $350 business license annual?', answer: 'Yes. CDA requires a $350 per year commercial pesticide applicator business license, which is in addition to individual applicator certification fees.' },
      { question: 'When is peak spray season in Colorado?', answer: 'Wheat heading in late May to early June on the eastern plains. Corn VT/R1 in July. Mountain agriculture has a compressed season from June through August.' },
      { question: 'Does Colorado have reciprocal licensing?', answer: 'Yes, with NE, WY, and NM. Contact CDA for current procedures.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbreviation: 'OK',
    region: 'great-plains',
    licensingAgency: 'Oklahoma Department of Agriculture, Food, and Forestry (ODAFF)',
    licensingAgencyUrl: 'https://ag.ok.gov',
    aerialCategory: 'Aerial category under ODAFF. FAA Part 137 must be filed with the Board before aerial license is issued.',
    examsRequired: 'Core + category exams. 70% passing. $50 total initial. $100/category/yr license.',
    examFees: '$50 initial certification. $100/category/yr license.',
    uniqueRules: [
      'FAA Part 137 must be filed with the Oklahoma Board before aerial license is issued (OK Statutes 2-3-82).',
      'Late renewal doubles fees + $100 penalty after 30 days.',
      '5-year recertification per category.',
    ],
    reciprocityStates: ['AR', 'IN', 'KS', 'LA', 'MN', 'NE', 'NM', 'TX'],
    renewalCycle: 'Annual cycle (Oct 1 or Jan 1 depending on company name). 5-year recertification.',
    ceRequirements: 'CEUs or re-exam per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.okstate.edu',
    topCrops: [
      { slug: 'wheat', name: 'Wheat', acreage: '4.5M acres', notes: 'Winter wheat. Heading late May.' },
      { slug: 'cotton', name: 'Cotton', acreage: '600K acres', notes: 'Southwestern OK' },
      { slug: 'corn', name: 'Corn', acreage: '400K acres', notes: 'Panhandle irrigated' },
    ],
    rateRange: '$12 to $18',
    neighboringStates: ['kansas', 'texas', 'arkansas', 'colorado', 'new-mexico'],
    description: 'Oklahoma requires FAA Part 137 to be filed with the state Board before issuing an aerial license, a unique pre-filing step. 4.5 million acres of winter wheat drive the primary demand.',
    aeoBlock: 'Oklahoma requires FAA Part 137 to be filed with the state Board before issuing an aerial license under OK Statutes 2-3-82. Winter wheat (4.5 million acres) drives primary demand with heading in late May. Rates run $12 to $18 per acre, with cotton defoliant in southwestern OK as a secondary market.',
    faqs: [
      { question: 'What is the Oklahoma Part 137 filing requirement?', answer: 'ODAFF requires your FAA Part 137 Agricultural Aircraft Operator Certificate to be filed with the Oklahoma Board before they will issue your aerial applicator license. This is a pre-filing step, not just a credential check.' },
      { question: 'What does drone spraying cost in Oklahoma?', answer: 'Wheat runs $12 to $16 per acre. Cotton defoliant in southwestern OK runs $14 to $18. Wind is a significant operational constraint statewide.' },
      { question: 'What happens if I renew late in Oklahoma?', answer: 'Late renewal doubles your fees plus a $100 penalty if more than 30 days past due. Plan renewal well ahead of your anniversary date.' },
      { question: 'Does Oklahoma have reciprocal licensing?', answer: 'Yes, with AR, IN, KS, LA, MN, NE, NM, and TX. Contact ODAFF for current requirements.' },
      { question: 'When is peak spray season in Oklahoma?', answer: 'Wheat heading in late May. Cotton mid-season insecticide July to August. Cotton defoliant September to October. Wind conditions limit daily windows much of the year.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'new-mexico',
    name: 'New Mexico',
    abbreviation: 'NM',
    region: 'great-plains',
    licensingAgency: 'New Mexico Department of Agriculture (NMDA)',
    licensingAgencyUrl: 'https://www.nmda.nmsu.edu',
    aerialCategory: 'Core + site/pest category (no separate aerial category)',
    examsRequired: 'Core + 1 site/pest category. $55/exam. License $75/yr.',
    examFees: '$55/exam. $75/yr license.',
    uniqueRules: [
      'No separate aerial category. Drone operators certify in the relevant use category.',
      'Annual renewal with 4 CEUs per year.',
    ],
    reciprocityStates: ['CO', 'OK', 'TX'],
    renewalCycle: 'Annual renewal.',
    ceRequirements: '4 CEUs per year.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.nmsu.edu',
    topCrops: [
      { slug: 'cotton', name: 'Cotton', acreage: '50K acres', notes: 'Southern NM' },
    ],
    rateRange: '$15 to $22',
    neighboringStates: ['texas', 'oklahoma', 'colorado', 'arizona'],
    description: 'New Mexico has no separate aerial category for drone operators. Agricultural acreage is limited, with the primary drone opportunities in pecan orchards, chile, and ranch operations.',
    aeoBlock: 'New Mexico has no separate aerial applicator category. Drone operators certify in the relevant use category with Core exam plus category at $55 per exam. Agricultural drone demand centers on pecan orchards, chile, and ranch operations in southern New Mexico. Rates run $15 to $22 per acre.',
    faqs: [
      { question: 'Does New Mexico have an aerial applicator category?', answer: 'No. Unlike most states, NMDA does not maintain a separate aerial category. Drone operators certify in the relevant use category (e.g., agricultural pest control) and the same license covers aerial application.' },
      { question: 'What crops use drone spraying in New Mexico?', answer: 'Pecan orchards in the Mesilla Valley, chile in southern NM, cotton, and ranch/rangeland operations. Row crop acreage is limited compared to other Great Plains states.' },
      { question: 'What does drone spraying cost in New Mexico?', answer: '$15 to $22 per acre. Higher than the Corn Belt due to small field sizes, remote locations, and few operators. Pecan orchard work commands premium rates.' },
      { question: 'Does New Mexico have reciprocal licensing?', answer: 'Case-by-case basis. CO, OK, and TX operators may only need the NM laws exam. Contact NMDA.' },
      { question: 'Is there much drone operator competition in New Mexico?', answer: 'Very little. Low agricultural acreage and small operator density mean less pricing pressure but also longer travel distances between jobs.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
