// NORTHEAST BATCH: 11 states. Final batch.

  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbreviation: 'PA',
    region: 'southeast',
    licensingAgency: 'Pennsylvania Department of Agriculture',
    licensingAgencyUrl: 'https://www.agriculture.pa.gov',
    aerialCategory: 'Category 25: Aerial Applicator',
    examsRequired: 'Core ($50) + Category 25 ($10). Business license $35/yr. Annual renewal $40.',
    examFees: 'Core $50. Cat 25 $10. Business $35/yr. Renewal $40.',
    uniqueRules: [
      'Penn State Extension publishes comprehensive drone licensing guide.',
      'Category 25 is a clean aerial applicator category.',
      'Broad reciprocity with 25+ states.',
    ],
    reciprocityStates: ['DE', 'FL', 'ID', 'IN', 'IA', 'MD', 'NJ', 'NY', 'OH', 'SC', 'VA', 'WV', 'WI', 'WY'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '6 Core + 10 Category 25 credits per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://extension.psu.edu',
    extensionUrl: 'https://extension.psu.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '1.3M acres', notes: 'Central and SE Pennsylvania' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '600K acres', notes: 'SE Pennsylvania' },
      { slug: 'orchards', name: 'Apples/Peaches', acreage: '25K acres', notes: 'Adams County fruit belt' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Chesapeake Bay watershed incentives' },
    ],
    rateRange: '$15 to $24',
    neighboringStates: ['new-york', 'new-jersey', 'maryland', 'west-virginia', 'ohio', 'delaware'],
    description: 'Pennsylvania has one of the broadest reciprocity networks (25+ states) and a clean Category 25 aerial pathway. Chesapeake Bay watershed cover crop incentives drive growing drone seeding demand.',
    aeoBlock: 'Pennsylvania uses Category 25 (Aerial Applicator) with reciprocity across 25+ states, one of the broadest networks in the US. Rates run $15 to $24 per acre across 1.3 million acres of corn, 600K acres of soybeans, and a growing cover crop seeding market driven by Chesapeake Bay watershed conservation incentives.',
    faqs: [
      { question: 'What does drone spraying cost in Pennsylvania?', answer: 'Row crops run $15 to $20 per acre. Orchard work in Adams County runs $20 to $24. Cover crop seeding $14 to $18. Smaller and more irregular fields than the Midwest push rates slightly higher.' },
      { question: 'What license do I need in Pennsylvania?', answer: 'FAA Part 107, Part 137, and PDA Core + Category 25 (Aerial Applicator). Core exam $50, Category 25 just $10. Business license $35/yr.' },
      { question: 'Does Pennsylvania have good reciprocity?', answer: 'Yes, with 25+ states including DE, FL, IN, IA, MD, NJ, NY, OH, VA, WV, and WI. One of the broadest reciprocity lists nationally.' },
      { question: 'Is cover crop seeding a big drone market here?', answer: 'Growing fast. Chesapeake Bay watershed conservation programs provide strong cost-share incentives for cover crops in SE Pennsylvania. Drone seeding into standing corn and soybeans in September is the primary window.' },
      { question: 'When is peak spray season in Pennsylvania?', answer: 'Corn VT/R1 in late July to early August. Soybean R2/R3 overlaps. Cover crop seeding September to October. Apple orchard programs run April through August.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbreviation: 'NY',
    region: 'southeast',
    licensingAgency: 'New York State DEC',
    licensingAgencyUrl: 'https://www.dec.ny.gov',
    aerialCategory: 'Category 11: Aerial Application',
    examsRequired: 'Core + Category 11 + 1 site/pest category (3 exams). $100/exam. Certification $450/3yr first category, $150 each additional.',
    examFees: '$100/exam. $450/3yr first category. $150 each additional.',
    uniqueRules: [
      'Among the highest exam and certification fees nationally ($100/exam, $450 first category).',
      '3 exams minimum.',
    ],
    reciprocityStates: ['NJ', 'CT', 'PA', 'VT'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '6 credits per 3-year cycle for Category 11. Other categories vary.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://cals.cornell.edu/cornell-cooperative-extension',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '1M acres', notes: 'Western NY and Finger Lakes' },
      { slug: 'grapes', name: 'Grapes', acreage: '35K acres', notes: 'Finger Lakes and Long Island AVAs' },
      { slug: 'orchards', name: 'Apples', acreage: '40K acres', notes: '#2 apple state after WA' },
    ],
    rateRange: '$16 to $28',
    neighboringStates: ['pennsylvania', 'new-jersey', 'connecticut', 'massachusetts', 'vermont'],
    description: 'New York has the highest exam fees in the Northeast at $100 per exam and $450 for first category certification. Finger Lakes wine grapes and Hudson Valley orchards provide high-value specialty crop demand.',
    aeoBlock: 'New York requires Category 11 (Aerial Application) with the highest exam fees in the Northeast: $100 per exam and $450 for 3-year first category certification. Rates run $16 to $28 per acre across 35K acres of Finger Lakes wine grapes, 40K acres of apples (#2 nationally), and 1 million acres of corn.',
    faqs: [
      { question: 'What does drone spraying cost in New York?', answer: 'Corn and soybeans $16 to $20 per acre. Apple orchards in the Hudson Valley $22 to $28. Wine grapes in the Finger Lakes $20 to $26. Higher than the Midwest due to smaller fields and fewer operators.' },
      { question: 'Why are New York licensing fees so high?', answer: '$100 per exam and $450 for the first 3-year category certification are among the highest nationally. Each additional category adds $150. Budget $700 to $1,000 for initial New York licensing.' },
      { question: 'Is the Finger Lakes a drone spray opportunity?', answer: 'Yes. Hillside vineyard blocks with steep grades make airblast impractical. Finger Lakes vineyards run 8 to 10 fungicide passes per season for downy and powdery mildew. Growing drone adoption.' },
      { question: 'Does New York have reciprocal licensing?', answer: 'Yes, with NJ, CT, PA, and VT. Contact DEC for specific procedures.' },
      { question: 'What about Long Island vineyards?', answer: 'Long Island (North Fork and Hamptons AVAs) adds about 3K acres of vineyards. Proximity to residential areas makes drones preferred over airblast for drift control. Premium rates reflect the market.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    abbreviation: 'MD',
    region: 'southeast',
    licensingAgency: 'Maryland Department of Agriculture (MDA)',
    licensingAgencyUrl: 'https://mda.maryland.gov/plants-pests/pages/licensing_and_certification.aspx',
    aerialCategory: 'Category 13: Aerial',
    examsRequired: 'Core + Category 13. $75/yr initial cert + $25 each additional. 1 year practical experience required.',
    examFees: '$75/yr initial. $25 each additional category.',
    uniqueRules: [
      '1 year practical experience required before certification exam.',
      '8 annual CE credits among highest nationally.',
      'Liability insurance required.',
      'Chesapeake Bay watershed cover crop conservation programs.',
    ],
    reciprocityStates: ['DE', 'PA', 'VA', 'WV'],
    renewalCycle: 'Annual.',
    ceRequirements: '8 credits annually for Category 13. Among the highest CE requirements nationally.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.umd.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '450K acres', notes: 'Eastern Shore' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '500K acres', notes: 'Eastern Shore' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Chesapeake Bay watershed incentives strong' },
    ],
    rateRange: '$16 to $24',
    neighboringStates: ['pennsylvania', 'delaware', 'virginia', 'west-virginia'],
    description: 'Maryland requires 1 year of practical experience before the aerial exam and 8 annual CE credits, among the highest nationally. Chesapeake Bay watershed cover crop incentives drive strong drone seeding demand on the Eastern Shore.',
    aeoBlock: 'Maryland requires Category 13 (Aerial) with 1 year practical experience before the exam and 8 annual CE credits, among the highest in the US. Chesapeake Bay watershed programs drive strong cover crop drone seeding demand. Rates run $16 to $24 per acre on the Eastern Shore.',
    faqs: [
      { question: 'What is the experience requirement?', answer: '1 year of practical experience in pest control before you can sit for the Category 13 aerial exam. This is unusual nationally and adds time to the certification pathway.' },
      { question: 'What does drone spraying cost in Maryland?', answer: '$16 to $24 per acre. Eastern Shore corn and soybeans at the low end. Cover crop seeding and specialty crops higher.' },
      { question: 'Is cover crop seeding a big market in Maryland?', answer: 'Yes. Maryland Chesapeake Bay watershed programs provide strong cost-share for cover crops. The Eastern Shore is one of the densest cover crop regions in the US. Drone seeding into standing corn in September is the primary window.' },
      { question: 'Why are CE requirements so high?', answer: '8 credits annually for Category 13, compared to 4 to 6 per year in most states. This reflects Maryland stricter environmental compliance stance in the Chesapeake Bay watershed.' },
      { question: 'Does Maryland have reciprocal licensing?', answer: 'Yes, with DE, PA, VA, and WV.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbreviation: 'NJ',
    region: 'southeast',
    licensingAgency: 'New Jersey Department of Environmental Protection (DEP)',
    licensingAgencyUrl: 'https://www.nj.gov/dep/enforcement/pcp',
    aerialCategory: 'Category 11: Aerial Applicator. 40 hours OJT required for Category 11.',
    examsRequired: 'Core + Category 11 + 1 additional category. ~$50/exam. License ~$100/yr. 40 hrs OJT.',
    examFees: '~$50/exam. ~$100/yr license.',
    uniqueRules: [
      '40 hours on-the-job training required specifically for Category 11.',
      'Dense population increases drift sensitivity and buffer zone requirements.',
    ],
    reciprocityStates: ['NY', 'CT', 'IN', 'OH', 'PA', 'RI', 'VT'],
    renewalCycle: '5-year cycle.',
    ceRequirements: '8 Core + 16 per category per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://njaes.rutgers.edu',
    topCrops: [
      { slug: 'soybeans', name: 'Soybeans', acreage: '100K acres', notes: 'South Jersey' },
      { slug: 'corn', name: 'Corn', acreage: '80K acres', notes: 'South Jersey' },
    ],
    rateRange: '$18 to $28',
    neighboringStates: ['new-york', 'pennsylvania', 'delaware'],
    description: 'New Jersey requires 40 hours of on-the-job training for Category 11 aerial certification. Dense population and small field sizes push rates to $18 to $28 per acre. Blueberry and cranberry bogs are specialty niches.',
    aeoBlock: 'New Jersey requires 40 hours of on-the-job training for Category 11 (Aerial Applicator), one of the few states with a mandatory OJT component. Dense population increases drift sensitivity. Rates run $18 to $28 per acre. Blueberry and cranberry operations in the Pine Barrens are specialty niches.',
    faqs: [
      { question: 'What is the 40-hour OJT requirement?', answer: 'New Jersey requires 40 hours of on-the-job training specifically for Category 11 aerial certification. This must be documented under supervision before you can apply for the license.' },
      { question: 'What does drone spraying cost in New Jersey?', answer: '$18 to $28 per acre. Small field sizes and dense population (drift sensitivity) push rates above neighboring PA and NY.' },
      { question: 'What crops use drones in New Jersey?', answer: 'Soybeans and corn in South Jersey, blueberries in the Pine Barrens, cranberry bogs, and vegetable farms. Small diversified farms are the norm rather than large-acreage operations.' },
      { question: 'Does New Jersey have reciprocal licensing?', answer: 'Yes, with NY, CT, IN, OH, PA, RI, and VT.' },
      { question: 'Is New Jersey practical for a drone spray business?', answer: 'As a secondary market for PA or NY based operators, yes. Total addressable acreage is too small for a NJ-only business, but specialty crop premiums (blueberries, cranberries, vegetables) make individual jobs profitable.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    abbreviation: 'CT',
    region: 'southeast',
    licensingAgency: 'Connecticut DEEP',
    licensingAgencyUrl: 'https://portal.ct.gov/deep',
    aerialCategory: 'Aerial category being formalized per HB 6289 (2024). Deadline March 2026.',
    examsRequired: 'Core + category. $200 to DEEP + $21 proctoring.',
    examFees: '$200 DEEP fee. $21 proctoring.',
    uniqueRules: [
      'HB 6289 (2024) mandated Commissioner to update regulations by March 2026 to authorize drones for crop treatment.',
      'Pre-existing aerial rules require per-application aerial permit (Form DEP-PEST-APP-100).',
      '200 to 300 ft buffer zone notifications required.',
      'Acreage-based permit fees $200 to $565.',
      '5-year certification cycle, longest in the US.',
    ],
    reciprocityStates: ['NY', 'NJ', 'MA'],
    renewalCycle: '5-year cycle (longest nationally).',
    ceRequirements: '12 CEU per category per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://cahnr.uconn.edu/extension',
    topCrops: [],
    rateRange: '$20 to $30',
    neighboringStates: ['new-york', 'massachusetts', 'rhode-island'],
    description: 'Connecticut is actively formalizing drone regulations under HB 6289 (2024) with a March 2026 deadline. Pre-existing rules require per-application aerial permits with acreage-based fees of $200 to $565. Contact DEEP for current drone status.',
    aeoBlock: 'Connecticut is actively formalizing drone spraying regulations under HB 6289 (2024) with a March 2026 implementation deadline. Current rules require per-application aerial permits (Form DEP-PEST-APP-100) with fees of $200 to $565 per application and 200 to 300 foot buffer zone notifications. Contact DEEP for current drone authorization status.',
    faqs: [
      { question: 'Are drones legal for crop spraying in Connecticut?', answer: 'HB 6289 (2024) mandated the DEEP Commissioner to update regulations by March 2026 to explicitly authorize drones. Current status should be confirmed directly with DEEP, as implementing regulations may still be in development.' },
      { question: 'What is the per-application permit?', answer: 'Connecticut requires Form DEP-PEST-APP-100 for each aerial application, with USGS maps, buffer zone notifications, and acreage-based fees of $200 to $565. This applies to drones as well as manned aircraft.' },
      { question: 'What does drone spraying cost in Connecticut?', answer: '$20 to $30 per acre. Small fields, dense population, buffer zone requirements, and per-application permit fees all push costs above neighboring states.' },
      { question: 'Does Connecticut have the longest certification cycle?', answer: 'Yes, at 5 years, tied with a few other states but the longest in this region. 12 CEU per category per 5-year cycle.' },
      { question: 'Does Connecticut have reciprocal licensing?', answer: 'Yes, with NY, NJ, and MA.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'delaware',
    name: 'Delaware',
    abbreviation: 'DE',
    region: 'southeast',
    licensingAgency: 'Delaware Department of Agriculture (DDA)',
    licensingAgencyUrl: 'https://agriculture.delaware.gov',
    aerialCategory: 'Category 11: Aerial Pest Control',
    examsRequired: 'Core + Category 11 + site category. $30/yr cert. $50/yr business. 70% passing. 2 years experience required.',
    examFees: '$30/yr cert. $50/yr business.',
    uniqueRules: [
      '2 years supervised practical experience required before certification exam.',
      'Chesapeake Bay watershed cover crop programs apply.',
    ],
    reciprocityStates: ['MD', 'NJ', 'PA', 'VA'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '4 credits for Category 11 per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.udel.edu/canr/cooperative-extension',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '170K acres', notes: 'Sussex County' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '170K acres', notes: 'Sussex County' },
      { slug: 'cover-crops', name: 'Cover Crops', acreage: 'Growing', notes: 'Chesapeake Bay incentives' },
    ],
    rateRange: '$16 to $24',
    neighboringStates: ['maryland', 'pennsylvania', 'new-jersey'],
    description: 'Delaware requires 2 years of supervised practical experience before the aerial certification exam. Small state with concentrated agriculture in Sussex County. Chesapeake Bay cover crop programs drive drone seeding demand.',
    aeoBlock: 'Delaware requires 2 years supervised practical experience before the Category 11 (Aerial Pest Control) exam. Agriculture is concentrated in Sussex County with 170K acres each of corn and soybeans. Chesapeake Bay watershed cover crop incentives drive drone seeding demand. Rates run $16 to $24 per acre.',
    faqs: [
      { question: 'What is the 2-year experience requirement?', answer: 'Delaware requires 2 years of supervised practical experience in pest control before you can sit for the Category 11 aerial certification exam. This is the longest experience requirement for aerial in the Northeast.' },
      { question: 'What does drone spraying cost in Delaware?', answer: '$16 to $24 per acre. Sussex County row crops at the low end, specialty and cover crop work higher.' },
      { question: 'Is Delaware big enough for a drone business?', answer: 'As a standalone market, barely. 340K combined corn and soybean acres in Sussex County is the entire addressable market. Most Delaware operators also serve MD, PA, and NJ.' },
      { question: 'Does Delaware have reciprocal licensing?', answer: 'Yes, with MD, NJ, PA, and VA.' },
      { question: 'Are cover crops important in Delaware?', answer: 'Yes. Chesapeake Bay watershed programs provide cost-share for cover crops. Drone seeding into standing corn in September is growing in Sussex County.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'rhode-island',
    name: 'Rhode Island',
    abbreviation: 'RI',
    region: 'southeast',
    licensingAgency: 'Rhode Island DEM',
    licensingAgencyUrl: 'https://dem.ri.gov',
    aerialCategory: 'No specific aerial category. Separate DEM aerial application permit required.',
    examsRequired: 'Core + use category + DEM aerial permit. Contact DEM at (401) 222-2781.',
    examFees: 'Contact DEM.',
    uniqueRules: [
      'Separate DEM aerial application permit required in addition to applicator certification.',
      'Smallest state. Minimal agricultural acreage.',
    ],
    reciprocityStates: ['NJ', 'CT', 'MA'],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'CE hours vary by license type.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://web.uri.edu/coopext',
    topCrops: [],
    rateRange: '$22 to $35',
    neighboringStates: ['massachusetts', 'connecticut'],
    description: 'Rhode Island requires a separate DEM aerial application permit. Smallest state with minimal agricultural acreage. Drone opportunities limited to small specialty farms and turf/landscape.',
    aeoBlock: 'Rhode Island requires a separate DEM aerial application permit in addition to standard applicator certification. Agricultural acreage is minimal. Drone opportunities are limited to small specialty farms, turf management, and landscape applications. Rates run $22 to $35 per acre.',
    faqs: [
      { question: 'Is there drone spray demand in Rhode Island?', answer: 'Very limited. Small specialty vegetable farms, turf management, and landscape pest control are the primary opportunities. Total agricultural acreage is the smallest of any state.' },
      { question: 'What does drone spraying cost?', answer: '$22 to $35 per acre. Small fields and few operators drive rates well above the national average.' },
      { question: 'What is the DEM aerial permit?', answer: 'A separate permit from RI DEM required for any aerial pesticide application. This is in addition to your applicator certification. Contact DEM at (401) 222-2781.' },
      { question: 'Does RI have reciprocal licensing?', answer: 'Limited. Confirm with DEM.' },
      { question: 'Is RI practical for a drone spray business?', answer: 'Only as part of a broader New England territory covering CT, MA, and RI combined. Standalone RI operations are not viable due to minimal acreage.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbreviation: 'MA',
    region: 'southeast',
    licensingAgency: 'Massachusetts MDAR',
    licensingAgencyUrl: 'https://www.mass.gov/pesticide-examination-and-licensing',
    aerialCategory: 'Category 11: Aerial Application',
    examsRequired: 'Core + Aerial + category. $50/yr cert. $28 online exam. 2 years experience required.',
    examFees: '$50/yr cert. $28 online exam.',
    uniqueRules: [
      '2 years practical experience required.',
      'Insurance required: $100K/$300K bodily injury, $100K property. Must include chemical drift coverage.',
      'Reciprocity at MDAR discretion (333 CMR 10.12).',
    ],
    reciprocityStates: ['CT', 'NY', 'NH', 'VT', 'RI'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '12 contact hours per 3-year cycle per category.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://ag.umass.edu/extension',
    topCrops: [
      { slug: 'orchards', name: 'Cranberries/Apples', acreage: '15K acres', notes: 'Cape Cod cranberry bogs, central MA apples' },
    ],
    rateRange: '$20 to $30',
    neighboringStates: ['connecticut', 'new-york', 'new-hampshire', 'vermont', 'rhode-island'],
    description: 'Massachusetts requires 2 years experience, $100K/$300K bodily injury insurance, and chemical drift coverage. Cranberry bogs on Cape Cod and central MA apple orchards are specialty drone niches.',
    aeoBlock: 'Massachusetts requires Category 11 (Aerial Application) with 2 years practical experience and insurance of $100K/$300K bodily injury plus $100K property including chemical drift coverage. Cranberry bogs and apple orchards are specialty drone niches. Rates run $20 to $30 per acre.',
    faqs: [
      { question: 'What insurance is required in Massachusetts?', answer: '$100,000/$300,000 bodily injury and $100,000 property damage. Critically, the policy must explicitly include chemical drift coverage, which is a separate endorsement most standard drone policies do not carry.' },
      { question: 'What does drone spraying cost in Massachusetts?', answer: '$20 to $30 per acre. Cranberry bog work and apple orchard spraying command premium rates. Row crop acreage is very limited.' },
      { question: 'Are cranberry bogs a drone opportunity?', answer: 'Yes. Cape Cod cranberry operations use aerial applications for pest and disease management. Drones handle the small, irregularly shaped bogs better than manned aircraft.' },
      { question: 'Does Massachusetts have reciprocal licensing?', answer: 'At MDAR discretion under 333 CMR 10.12. CT, NY, NH, VT, and RI operators may qualify. Contact MDAR.' },
      { question: 'Is the 2-year experience requirement common?', answer: 'It is shared by MD and DE in the region but unusual nationally. Most states have no experience requirement beyond passing the exams.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'vermont',
    name: 'Vermont',
    abbreviation: 'VT',
    region: 'southeast',
    licensingAgency: 'Vermont Agency of Agriculture, Food and Markets',
    licensingAgencyUrl: 'https://agriculture.vermont.gov',
    aerialCategory: 'Category 11: Aerial. Plus mandatory Aerial Permit from the Secretary with 30-day public comment.',
    examsRequired: 'Core + Category 11 + Aerial Permit application. $30/category/yr ($120 max). Retake $25. 75% passing.',
    examFees: '$30/category/yr. $120 max. Retake $25. 75% passing (higher than most states).',
    uniqueRules: [
      'Aerial Permit required for all aerial applications (including drones) with 30-day public comment period.',
      'Buffer distances set by the Secretary.',
      'Must comply with VT Agency of Transportation rules.',
      'Aerial exam must be taken in person.',
      '75% passing score (higher than the 70% standard in most states).',
    ],
    reciprocityStates: ['NY', 'NJ', 'RI', 'PA'],
    renewalCycle: '5-year cycle.',
    ceRequirements: '16 credits per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://agriculture.vermont.gov',
    extensionUrl: 'https://www.uvm.edu/extension',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '85K acres', notes: 'Dairy silage corn' },
      { slug: 'orchards', name: 'Apples', acreage: '3K acres', notes: 'Champlain Valley' },
    ],
    rateRange: '$20 to $30',
    neighboringStates: ['new-york', 'new-hampshire', 'massachusetts'],
    description: 'Vermont requires an Aerial Permit with a 30-day public comment period for all aerial applications including drones. Higher 75% passing score and in-person aerial exam requirement add barriers.',
    aeoBlock: 'Vermont requires a mandatory Aerial Permit from the Secretary with a 30-day public comment period for all aerial applications including drones. The aerial exam requires 75 percent passing (above the national 70 percent standard) and must be taken in person. Rates run $20 to $30 per acre on limited agricultural acreage.',
    faqs: [
      { question: 'What is the Aerial Permit with public comment?', answer: 'Vermont requires a permit application for every aerial pesticide application, including drones, with a 30-day public comment period. Buffer distances are set by the Secretary. This is the most restrictive aerial permitting process in the Northeast.' },
      { question: 'What does drone spraying cost in Vermont?', answer: '$20 to $30 per acre. Very limited acreage, small fields, and few operators push rates above neighboring states.' },
      { question: 'Is the higher passing score difficult?', answer: '75 percent vs the national standard of 70 percent. Marginal difference but catches some test-takers who would pass in other states. The in-person exam requirement also adds a travel commitment.' },
      { question: 'What crops use drones in Vermont?', answer: 'Dairy silage corn (85K acres), Champlain Valley apples, and specialty vegetables. Total acreage is very small.' },
      { question: 'Does Vermont have reciprocal licensing?', answer: 'Yes, with NY, NJ, RI, and PA.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    abbreviation: 'NH',
    region: 'southeast',
    licensingAgency: 'New Hampshire Division of Pesticide Control',
    licensingAgencyUrl: 'https://www.agriculture.nh.gov',
    aerialCategory: 'Category J: Aerial Application',
    examsRequired: 'Core + Category J. Contact (603) 271-3550 for fees.',
    examFees: 'Contact Division of Pesticide Control.',
    uniqueRules: [
      'Minimal agricultural acreage.',
      'Primary drone opportunities in forestry and landscape pest management.',
    ],
    reciprocityStates: ['VT', 'MA', 'ME'],
    renewalCycle: '5-year cycle.',
    ceRequirements: '12 credits per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.unh.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '20K acres', notes: 'Dairy silage' },
    ],
    rateRange: '$22 to $32',
    neighboringStates: ['vermont', 'massachusetts', 'maine'],
    description: 'New Hampshire has Category J (Aerial Application) with minimal agricultural acreage. Primary drone opportunities are in forestry pest management, blueberry operations, and apple orchards.',
    aeoBlock: 'New Hampshire uses Category J (Aerial Application) with minimal agricultural crop acreage. Primary drone opportunities are forestry pest management, blueberry operations, and small apple orchards. Rates run $22 to $32 per acre.',
    faqs: [
      { question: 'Is there drone spray demand in New Hampshire?', answer: 'Limited. Forestry pest management, small apple orchards, blueberry operations, and landscape pest control are the main niches. Total crop acreage is very small.' },
      { question: 'What does drone spraying cost?', answer: '$22 to $32 per acre. Small fields, hilly terrain, and very few operators push rates above the national average.' },
      { question: 'What license do I need?', answer: 'FAA Part 107, Part 137, and NH Division of Pesticide Control Core + Category J. Contact (603) 271-3550 for current fees and exam schedule.' },
      { question: 'Does NH have reciprocal licensing?', answer: 'Yes, with VT, MA, and ME.' },
      { question: 'Is NH practical for a drone spray business?', answer: 'Only as part of a broader New England territory. Most NH drone operators also serve VT, MA, and ME.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'maine',
    name: 'Maine',
    abbreviation: 'ME',
    region: 'southeast',
    licensingAgency: 'Maine Board of Pesticides Control (BPC)',
    licensingAgencyUrl: 'https://www.maine.gov/dacf/php/pesticides/applicators/licensing.html',
    aerialCategory: 'Category 11: Aerial Pest Control',
    examsRequired: 'Core + Category 11. $10/exam. 80% passing (highest in the US). $105 license.',
    examFees: '$10/exam. $105 license.',
    uniqueRules: [
      '80% passing score, the highest in the US.',
      'Category 11 is not standalone; Master Applicator must be employed first.',
      'Firm license $300 required.',
      'Reciprocity for pest management emergencies only.',
    ],
    reciprocityStates: [],
    renewalCycle: '3-year cycle.',
    ceRequirements: 'Operator: 6 credits per 3 years. Master: 9 credits per 3 years.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.umaine.edu',
    topCrops: [
      { slug: 'orchards', name: 'Blueberries', acreage: '44K acres', notes: '#1 wild blueberry state' },
    ],
    rateRange: '$20 to $32',
    neighboringStates: ['new-hampshire'],
    description: 'Maine has the highest exam passing score in the US at 80% and requires a Master Applicator on staff before Category 11 aerial certification. Wild blueberry operations (44K acres) are the primary drone niche.',
    aeoBlock: 'Maine requires the highest exam passing score in the US at 80 percent for Category 11 (Aerial Pest Control), and a Master Applicator must be employed by the firm before aerial certification is issued. Wild blueberry operations (44K acres, #1 nationally) are the primary drone opportunity. Rates run $20 to $32 per acre.',
    faqs: [
      { question: 'Why is Maine passing score 80%?', answer: 'Maine BPC sets the passing threshold at 80 percent, compared to 70 percent in most states and 75 percent in Vermont. This is the highest exam standard in the US for aerial pesticide applicators.' },
      { question: 'What is the Master Applicator requirement?', answer: 'Maine requires a Master Applicator to be employed by the firm before Category 11 aerial certification can be issued to individual operators. Master certification requires 9 CE credits per 3-year cycle versus 6 for standard operators.' },
      { question: 'Are wild blueberries a drone opportunity?', answer: 'Yes. Maine grows 44K acres of wild blueberries, the most in the US. Aerial fungicide and insecticide applications during bloom and fruit set are standard practice. Drones handle the small, irregular field shapes better than manned aircraft.' },
      { question: 'Does Maine have reciprocal licensing?', answer: 'Emergency only, for pest management emergencies. No standard reciprocity. All operators must test in Maine.' },
      { question: 'What does drone spraying cost in Maine?', answer: '$20 to $32 per acre. Blueberry operations and apple orchards at the high end. Very limited row crop acreage.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
