// DELTA + SOUTHEAST BATCH: Add these 10 state objects to states array.

  {
    slug: 'mississippi',
    name: 'Mississippi',
    abbreviation: 'MS',
    region: 'mississippi-delta',
    licensingAgency: 'Mississippi Department of Agriculture and Commerce (MDAC)',
    licensingAgencyUrl: 'https://www.mdac.ms.gov',
    aerialCategory: 'Category 11: Aerial Applicator + Ag Aviation license',
    examsRequired: 'Written exam. 3-year certification. Ag Aviation license. Fees unverified.',
    examFees: 'Fees unverified. Contact MDAC.',
    uniqueRules: [
      'UAV FAQ published but regulations still evolving.',
      'Hormone herbicide restrictions apply to aerial application.',
      'Special use permits required for research drone applications.',
    ],
    reciprocityStates: ['AL', 'LA', 'AR', 'TN'],
    renewalCycle: '3-year cycle.',
    ceRequirements: 'Specific hours unverified. Contact MDAC.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://www.mdac.ms.gov',
    extensionUrl: 'https://extension.msstate.edu',
    topCrops: [
      { slug: 'rice', name: 'Rice', acreage: '200K acres', notes: 'Delta region, 100% aerial treated' },
      { slug: 'cotton', name: 'Cotton', acreage: '600K acres', notes: 'Defoliant Sep to Oct' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '2.1M acres', notes: 'Delta soybeans' },
      { slug: 'corn', name: 'Corn', acreage: '800K acres', notes: 'Delta region' },
    ],
    rateRange: '$14 to $18',
    neighboringStates: ['arkansas', 'louisiana', 'alabama', 'tennessee'],
    description: 'Mississippi Delta rice and cotton drive strong aerial application demand. Regulations are evolving for drones, with a UAV FAQ published but full drone-specific rules still in development.',
    aeoBlock: 'Mississippi has 2.1 million acres of soybeans, 800K acres of corn, and 600K acres of cotton in the Delta, with rates of $14 to $18 per acre. MDAC requires Category 11 (Aerial Applicator) plus an Ag Aviation license. Drone-specific regulations are evolving, with a UAV FAQ published and rules under active development.',
    faqs: [
      { question: 'What does drone spraying cost in Mississippi?', answer: 'Delta rates run $14 to $18 per acre for rice, cotton, and soybean applications. Strong manned aerial applicator competition keeps drone pricing moderate.' },
      { question: 'Are Mississippi drone regulations finalized?', answer: 'Partially. MDAC has published a UAV FAQ and requires Category 11 plus Ag Aviation licensing, but drone-specific rules are still evolving. Contact MDAC directly for current requirements.' },
      { question: 'What crops drive drone demand in Mississippi?', answer: 'Rice (100% aerial treated), cotton (defoliant Sep to Oct), soybeans (R2/R3 fungicide), and corn. The Delta region is the primary market.' },
      { question: 'Does Mississippi have reciprocal licensing?', answer: 'Yes, with AL, LA, AR, and TN. Contact MDAC for current procedures.' },
      { question: 'Is the Mississippi Delta a good market for drone operators?', answer: 'Yes, but competitive. Manned aerial applicators have deep roots here. Drones win on rice paddies (ground access impossible), drift-sensitive soybean borders, and small levee fields where airplane turns are inefficient.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    abbreviation: 'AR',
    region: 'mississippi-delta',
    licensingAgency: 'Arkansas Department of Agriculture',
    licensingAgencyUrl: 'https://www.agriculture.arkansas.gov',
    aerialCategory: 'Pilot authorization added to license. CAT license invalid for drone use.',
    examsRequired: 'Core + category. $10/yr or $45/5yr individual. $100/location firm.',
    examFees: '$10/yr or $45/5yr. $100/location firm license.',
    uniqueRules: [
      'Drones classified as aircraft; must follow aerial application sections of federal pesticide labels.',
      'Private applicator license alone is insufficient; must obtain specific "pilot authorization" on license.',
      'Commercial Applicator Technician (CAT) license holders cannot perform drone applications.',
      'Drone-applied pesticides restricted to agricultural crop settings only (no golf courses, lawns, turf, ornamentals).',
      'No reciprocity with any state.',
    ],
    reciprocityStates: [],
    renewalCycle: '5-year cycle. Recertification training.',
    ceRequirements: 'Recertification training every 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: 'https://www.agriculture.arkansas.gov',
    extensionUrl: 'https://www.uaex.uada.edu',
    topCrops: [
      { slug: 'rice', name: 'Rice', acreage: '1.2M acres', notes: '#1 rice state. 100% aerial treated at heading.' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '3.2M acres', notes: 'Delta soybeans' },
      { slug: 'cotton', name: 'Cotton', acreage: '500K acres', notes: 'Eastern AR Delta' },
      { slug: 'corn', name: 'Corn', acreage: '600K acres', notes: 'Delta region' },
    ],
    rateRange: '$14 to $18',
    neighboringStates: ['mississippi', 'louisiana', 'missouri', 'tennessee', 'oklahoma', 'texas'],
    description: 'Arkansas is the #1 rice state at 1.2 million acres, effectively 100% aerial treated. No reciprocity with any state. CAT license holders cannot fly drones, and drone pesticide application is restricted to agricultural crops only.',
    aeoBlock: 'Arkansas is the #1 US rice state at 1.2 million acres, effectively 100 percent aerial treated at heading stage. Drone operators must obtain a specific "pilot authorization" on their license; CAT licenses are invalid for drones. No reciprocity with any state. Rates run $14 to $18 per acre.',
    faqs: [
      { question: 'Why is Arkansas the top state for drone spraying on rice?', answer: 'Arkansas grows 1.2 million acres of rice, all requiring aerial treatment for heading-stage fungicide because flooded paddies make ground equipment impossible. Drones are taking rapid share from airplanes on drift-sensitive borders and small levee fields.' },
      { question: 'Can I use a CAT license for drone spraying in Arkansas?', answer: 'No. Arkansas explicitly prohibits Commercial Applicator Technician (CAT) license holders from performing drone applications. You must hold a full commercial applicator license with pilot authorization.' },
      { question: 'Does Arkansas have reciprocal licensing?', answer: 'No. Arkansas does not offer reciprocity with any state. All operators must test in Arkansas regardless of credentials held elsewhere.' },
      { question: 'Can I spray golf courses or lawns by drone in Arkansas?', answer: 'No. Arkansas restricts drone-applied pesticides to agricultural crop settings only. Golf courses, home lawns, turf, and ornamentals are excluded.' },
      { question: 'What does drone spraying cost in Arkansas?', answer: '$14 to $18 per acre for rice and cotton. Large blocks over 500 acres sometimes negotiate $12 to $14. Grand Prairie and Delta regions are the primary markets.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    abbreviation: 'LA',
    region: 'mississippi-delta',
    licensingAgency: 'Louisiana Department of Agriculture and Forestry (LDAF)',
    licensingAgencyUrl: 'https://www.ldaf.la.gov/plants/pesticides/pesticide-licensing',
    aerialCategory: 'Category 11: Aerial Applicator + Aerial Owner Operator License',
    examsRequired: 'General Standards (free) + Category 11 ($50). 70% passing.',
    examFees: 'GS free. Cat 11 $50. Aerial Owner Operator License $200 resident, $500 non-resident. Equipment $50/yr. $20/yr renewal.',
    uniqueRules: [
      'Mandatory LSU AgCenter Drone Safety Program (self-paced online course) required before certification.',
      'Aerial Owner Operator License: $200 for LA residents, $500 for non-residents.',
      '$50/yr per piece of mechanically-powered spray equipment.',
      'Liability insurance of at least $50,000 required.',
      'Distinguishes between Drone Operator License (own-farm) and full Aerial Applicator License (commercial).',
    ],
    reciprocityStates: ['AL', 'AR', 'MS', 'TX'],
    renewalCycle: '3-year cycle. Recertification meeting or retest. $20/yr renewal.',
    ceRequirements: 'Recertification meeting or retest every 3 years.',
    droneSpecificCredential: true,
    droneGuidanceUrl: 'https://store.lsuagcenter.com/p-2619-drone-safety-program.aspx',
    extensionUrl: 'https://www.lsuagcenter.com',
    topCrops: [
      { slug: 'rice', name: 'Rice', acreage: '400K acres', notes: 'SW Louisiana rice' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '1.1M acres', notes: 'Northern LA' },
      { slug: 'cotton', name: 'Cotton', acreage: '250K acres', notes: 'NE Louisiana' },
    ],
    rateRange: '$14 to $20',
    neighboringStates: ['mississippi', 'arkansas', 'texas'],
    description: 'Louisiana is the only state that mandates a pre-certification drone safety training course (LSU AgCenter Drone Safety Program). Non-resident Aerial Owner Operator License is $500, the highest non-resident fee in the Delta.',
    aeoBlock: 'Louisiana mandates the LSU AgCenter Drone Safety Program before drone pesticide certification, the only state with a mandatory pre-certification drone course. Non-resident Aerial Owner Operator License is $500. Rates run $14 to $20 per acre across 400K acres of rice and 1.1 million acres of soybeans.',
    faqs: [
      { question: 'What is the LSU AgCenter Drone Safety Program?', answer: 'A mandatory self-paced online course through LSU AgCenter Moodle platform. You must complete it and have the certificate sent to LDAF before applying for drone pesticide certification. It covers safe flight procedures, calibration, and regulatory compliance.' },
      { question: 'How much does the non-resident license cost in Louisiana?', answer: '$500 for the Aerial Owner Operator License (vs $200 for LA residents), plus $50/yr per piece of spray equipment. This is the highest non-resident aerial fee in the Delta region.' },
      { question: 'What does drone spraying cost in Louisiana?', answer: '$14 to $20 per acre. Rice at $14 to $18, soybeans at $12 to $16, cotton defoliant at $16 to $20. SW Louisiana rice and NE Louisiana cotton are the primary markets.' },
      { question: 'Does Louisiana distinguish between own-farm and commercial drone use?', answer: 'Yes. LDAF has a Drone Operator License for farmers spraying only their own land and a full Aerial Applicator License for commercial for-hire work. Different requirements and fees apply.' },
      { question: 'Does Louisiana have reciprocal licensing?', answer: 'Yes, with AL, AR, MS, TX. Exam waiver may be available for reciprocal applicants. Contact LDAF.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'alabama',
    name: 'Alabama',
    abbreviation: 'AL',
    region: 'southeast',
    licensingAgency: 'Alabama Department of Agriculture and Industries',
    licensingAgencyUrl: 'https://agi.alabama.gov',
    aerialCategory: 'Aerial category with insurance requirement. Custom Business License for aerial for-hire.',
    examsRequired: 'Core + category exams. Contact ADAI for fees.',
    examFees: 'Contact ADAI for current fees.',
    uniqueRules: [
      'Insurance required for aerial mode.',
      'Custom Business License required for for-hire aerial operations.',
    ],
    reciprocityStates: ['FL', 'GA', 'IN', 'LA', 'MS', 'OH', 'SC', 'TN'],
    renewalCycle: '3 to 5 year cycle (varies by category).',
    ceRequirements: 'Contact ADAI for current CE requirements.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.aces.edu',
    topCrops: [
      { slug: 'cotton', name: 'Cotton', acreage: '450K acres', notes: 'Central and southern AL' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '350K acres', notes: 'Northern AL' },
      { slug: 'corn', name: 'Corn', acreage: '300K acres', notes: 'Northern AL' },
    ],
    rateRange: '$16 to $24',
    neighboringStates: ['mississippi', 'tennessee', 'georgia', 'florida'],
    description: 'Alabama requires insurance and a Custom Business License for aerial for-hire drone operations. Cotton at 450K acres is the primary market, with rates of $16 to $24 per acre.',
    aeoBlock: 'Alabama requires insurance and a Custom Business License for for-hire aerial drone operations. Cotton (450K acres) is the primary crop, with rates of $16 to $24 per acre. Reciprocity with 8 states including FL, GA, MS, and TN.',
    faqs: [
      { question: 'What does drone spraying cost in Alabama?', answer: '$16 to $24 per acre. Cotton defoliant and mid-season insecticide at the high end, soybean fungicide at the low end.' },
      { question: 'What is the Custom Business License?', answer: 'Alabama requires a separate Custom Business License for aerial for-hire operations. This is in addition to individual applicator certification.' },
      { question: 'What crops drive drone demand in Alabama?', answer: 'Cotton (450K acres) in central and southern Alabama, soybeans and corn in northern Alabama. Peanut and pecan operations add specialty demand.' },
      { question: 'Does Alabama have reciprocal licensing?', answer: 'Yes, with FL, GA, IN, LA, MS, OH, SC, and TN. One of the broader reciprocity lists in the Southeast.' },
      { question: 'Is Alabama a good market for new drone operators?', answer: 'Moderate. Lower operator density than the Corn Belt means less competition but also smaller total acreage. Operators who serve both cotton and specialty crops have the best year-round utilization.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbreviation: 'GA',
    region: 'southeast',
    licensingAgency: 'Georgia Department of Agriculture (GDA)',
    licensingAgencyUrl: 'https://agr.georgia.gov',
    aerialCategory: 'Category 34: Aerial Methods. Recognizes both Part 107 and Part 137.',
    examsRequired: 'Core + site category + Category 34 (FAA proof required). $45/exam. $90 license. 70% passing.',
    examFees: '$45/exam. $90 license.',
    uniqueRules: [
      'Category 34 requires proof of FAA certification (Part 107 and/or Part 137).',
      'Category 34 has 0 CE hours (CE comes from site categories).',
      'Pesticide Contractor License required.',
    ],
    reciprocityStates: ['AL', 'FL', 'SC', 'TN', 'NC'],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'Category 34 = 0 CE hours. CE earned through site categories.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.uga.edu',
    topCrops: [
      { slug: 'cotton', name: 'Cotton', acreage: '1.2M acres', notes: '#2 cotton state' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '200K acres', notes: 'Southern GA' },
    ],
    rateRange: '$16 to $26',
    neighboringStates: ['alabama', 'florida', 'south-carolina', 'north-carolina', 'tennessee'],
    description: 'Georgia is the #2 cotton state at 1.2 million acres. Category 34 (Aerial Methods) uniquely requires FAA proof at the state level and has zero CE hours of its own.',
    aeoBlock: 'Georgia is the #2 US cotton state at 1.2 million acres, with Category 34 (Aerial Methods) requiring FAA proof and a Pesticide Contractor License. Rates run $16 to $26 per acre. Peanuts, pecans, and blueberries add specialty crop demand beyond cotton.',
    faqs: [
      { question: 'What does drone spraying cost in Georgia?', answer: 'Cotton defoliant runs $16 to $22 per acre. Pecan and blueberry orchard work runs $22 to $26. Row crop fungicide at the lower end.' },
      { question: 'Does Georgia require FAA proof for state licensing?', answer: 'Yes. Category 34 (Aerial Methods) requires you to show FAA Part 107 and/or Part 137 documentation as part of the state certification. This is unusual; most states do not formally verify FAA credentials.' },
      { question: 'What is the Pesticide Contractor License?', answer: 'Georgia requires commercial operators to hold both individual applicator certification and a Pesticide Contractor License for the business entity.' },
      { question: 'What specialty crops use drones in Georgia?', answer: 'Peanuts (800K acres), pecans (180K acres), and blueberries (25K acres) all have growing drone adoption. Peach orchards in central Georgia are an emerging niche.' },
      { question: 'Does Georgia have reciprocal licensing?', answer: 'Yes, with any EPA-approved state. Special agreement with Mississippi. Contact GDA for specific procedures.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbreviation: 'FL',
    region: 'southeast',
    licensingAgency: 'Florida Department of Agriculture and Consumer Services (FDACS)',
    licensingAgencyUrl: 'https://www.fdacs.gov',
    aerialCategory: 'Aerial Pest Control (Ch. 487 F.S.)',
    examsRequired: 'Core + Aerial + site category. No exam fee. $250 commercial license.',
    examFees: 'No exam fee. $250 commercial license.',
    uniqueRules: [
      'All aircraft including drones must register annually with FDACS.',
      'Insurance or surety bond required.',
      'No exam fee is unusual nationally.',
      '24 separate pest control categories; operators must certify in each relevant one.',
    ],
    reciprocityStates: ['AL', 'GA', 'SC'],
    renewalCycle: '4-year cycle.',
    ceRequirements: '4 Core + 16 Aerial CEU per 4-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://ifas.ufl.edu',
    topCrops: [
      { slug: 'orchards', name: 'Citrus', acreage: '375K acres', notes: 'Asian citrus psyllid management' },
    ],
    rateRange: '$18 to $28',
    neighboringStates: ['georgia', 'alabama'],
    description: 'Florida has 24 pest control categories and no exam fees, an unusual combination. Citrus (375K acres) with Asian citrus psyllid management is the primary drone opportunity. All aircraft must register annually with FDACS.',
    aeoBlock: 'Florida requires Aerial Pest Control certification under Chapter 487 with no exam fee but a $250 commercial license and annual aircraft registration with FDACS. Citrus (375K acres) drives the primary drone demand, with Asian citrus psyllid management requiring frequent low-volume insecticide applications. Rates run $18 to $28 per acre.',
    faqs: [
      { question: 'What does drone spraying cost in Florida?', answer: '$18 to $28 per acre. Citrus insecticide at the high end, row crop and pasture applications at the low end.' },
      { question: 'Do I need to register my drone with FDACS?', answer: 'Yes. All aircraft including drones must register annually with FDACS for aerial pesticide application. This is in addition to FAA registration.' },
      { question: 'Is there really no exam fee in Florida?', answer: 'Correct. FDACS does not charge for pesticide applicator exams. The $250 commercial license fee is the main cost.' },
      { question: 'What is the Asian citrus psyllid opportunity?', answer: 'The psyllid transmits citrus greening disease. Management requires frequent (every 2 to 4 weeks) low-volume insecticide applications during new flush growth. Drones handle this more precisely than airblast sprayers, especially near residential areas.' },
      { question: 'How many pest control categories does Florida have?', answer: '24 separate categories. Operators must certify in each relevant one. This is the most granular category system in the US.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbreviation: 'SC',
    region: 'southeast',
    licensingAgency: 'Clemson University Department of Pesticide Regulation',
    licensingAgencyUrl: 'https://www.clemson.edu/public/regulatory/pesticide-regulation',
    aerialCategory: 'Category 11: Aerial Applicator',
    examsRequired: 'Core ($75) + Category 11 ($50). License $50. $50K spray insurance required.',
    examFees: 'Core $75. Category 11 $50. License $50.',
    uniqueRules: [
      '$50,000 spray insurance required.',
      'Licensing administered by Clemson University, not a state agency.',
      '$50 reciprocal fee for out-of-state operators.',
    ],
    reciprocityStates: ['AL', 'GA', 'FL', 'NC', 'TN', 'VA'],
    renewalCycle: '5-year cycle.',
    ceRequirements: 'CCUs vary by category per 5-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.clemson.edu/extension',
    topCrops: [
      { slug: 'cotton', name: 'Cotton', acreage: '250K acres', notes: 'Coastal plain' },
      { slug: 'soybeans', name: 'Soybeans', acreage: '350K acres', notes: 'Pee Dee region' },
    ],
    rateRange: '$16 to $24',
    neighboringStates: ['north-carolina', 'georgia'],
    description: 'South Carolina licensing is uniquely administered by Clemson University, not a state agency. $50K spray insurance required. Reciprocity with 13 states at a $50 fee.',
    aeoBlock: 'South Carolina pesticide licensing is administered by Clemson University Department of Pesticide Regulation, with Category 11 (Aerial Applicator) and $50,000 spray insurance required. Reciprocity available with 13 states at $50. Rates run $16 to $24 per acre on cotton and soybeans.',
    faqs: [
      { question: 'Why does Clemson handle pesticide licensing?', answer: 'South Carolina delegates pesticide applicator regulation to Clemson University Department of Pesticide Regulation rather than a state agriculture department. Exams, licensing, and enforcement all run through Clemson.' },
      { question: 'What insurance is required?', answer: '$50,000 spray insurance minimum. This is lower than Ohio ($100K/$300K) but still a mandatory requirement.' },
      { question: 'What does drone spraying cost in South Carolina?', answer: '$16 to $24 per acre. Cotton and soybean applications in the coastal plain and Pee Dee region.' },
      { question: 'Does South Carolina have reciprocal licensing?', answer: 'Yes, with 13 states including AL, GA, FL, NC, TN, VA. $50 reciprocal fee.' },
      { question: 'What crops drive drone demand?', answer: 'Cotton (250K acres) and soybeans (350K acres) are primary. Peach orchards and tobacco add specialty demand.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbreviation: 'NC',
    region: 'southeast',
    licensingAgency: 'NC Department of Agriculture and Consumer Services',
    licensingAgencyUrl: 'https://www.ncagr.gov',
    aerialCategory: 'Aerial Methods category + specialty category. Aircraft inspection $25/aircraft.',
    examsRequired: 'Core ($50) + Aerial Methods ($50) + specialty ($20 each). License $75/yr.',
    examFees: 'Core/Aerial $50 each. Specialty $20. License $75/yr. Aircraft inspection $25.',
    uniqueRules: [
      'Aircraft inspection fee of $25 per aircraft.',
      '3 exams minimum: Core, Aerial Methods, and at least one specialty category.',
    ],
    reciprocityStates: ['KY', 'SC', 'TN', 'VA'],
    renewalCycle: '2-year cycle for aerial certification.',
    ceRequirements: '4 hours per 2-year cycle (aerial certification).',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://www.ces.ncsu.edu',
    topCrops: [
      { slug: 'soybeans', name: 'Soybeans', acreage: '1.6M acres', notes: 'Coastal plain' },
      { slug: 'corn', name: 'Corn', acreage: '900K acres', notes: 'Eastern NC' },
      { slug: 'cotton', name: 'Cotton', acreage: '350K acres', notes: 'Southern NC' },
    ],
    rateRange: '$16 to $25',
    neighboringStates: ['south-carolina', 'virginia', 'tennessee', 'georgia'],
    description: 'North Carolina charges a per-aircraft inspection fee of $25 and requires 3 minimum exams. Tobacco in the Piedmont and Coastal Plain adds high-value specialty crop demand.',
    aeoBlock: 'North Carolina requires Core, Aerial Methods, and specialty exams with a $25 per-aircraft inspection fee. Rates run $16 to $25 per acre across 1.6 million acres of soybeans, 900K acres of corn, and high-value tobacco in the Piedmont and Coastal Plain.',
    faqs: [
      { question: 'What does drone spraying cost in North Carolina?', answer: 'Row crops run $16 to $20 per acre. Tobacco and specialty crops run $22 to $25. Eastern NC coastal plain has the most demand.' },
      { question: 'What is the aircraft inspection fee?', answer: 'NC charges $25 per aircraft for inspection. Each drone in your fleet needs a separate inspection.' },
      { question: 'What crops drive drone demand in North Carolina?', answer: 'Soybeans (1.6M acres), corn (900K acres), cotton (350K acres), and tobacco. Sweet potatoes in the Sandhills are an emerging niche.' },
      { question: 'Does NC have reciprocal licensing?', answer: 'Yes, with KY, SC, TN, and VA. Limited compared to Midwest states.' },
      { question: 'Is tobacco a good drone spray market?', answer: 'Yes. Tobacco plants reach waist height by mid-season, making ground sprayer access damaging. Blue mold and black shank fungicides apply well by drone without crop damage.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbreviation: 'VA',
    region: 'southeast',
    licensingAgency: 'Virginia Department of Agriculture and Consumer Services (VDACS)',
    licensingAgencyUrl: 'https://www.vdacs.virginia.gov',
    aerialCategory: 'Category 11: Aerial Pesticide Application',
    examsRequired: 'Core + Category 11. Application $25 (non-refundable). Renewal fee eliminated 2022.',
    examFees: '$25 application (non-refundable). Renewal fee eliminated in 2022.',
    uniqueRules: [
      'Must provide FAA Part 107 + Part 137 documentation to VDACS.',
      'Renewal fee was eliminated in 2022, making Virginia one of the cheapest states for ongoing licensing.',
    ],
    reciprocityStates: ['KY', 'NC', 'SC', 'WV', 'MD', 'DE'],
    renewalCycle: 'Biennial (every 2 years). Attend 1 recertification session per category.',
    ceRequirements: '1 recertification session per category per 2-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://ext.vt.edu',
    topCrops: [
      { slug: 'soybeans', name: 'Soybeans', acreage: '550K acres', notes: 'Eastern VA' },
      { slug: 'corn', name: 'Corn', acreage: '400K acres', notes: 'Shenandoah Valley' },
      { slug: 'grapes', name: 'Grapes', acreage: '4K acres', notes: 'Growing wine industry' },
    ],
    rateRange: '$16 to $26',
    neighboringStates: ['north-carolina', 'west-virginia', 'kentucky', 'maryland'],
    description: 'Virginia eliminated its renewal fee in 2022, making ongoing licensing among the cheapest in the US. The growing wine industry (4K acres of vineyards) adds specialty demand.',
    aeoBlock: 'Virginia requires Category 11 (Aerial Pesticide Application) with a $25 non-refundable application and no renewal fee (eliminated 2022). Rates run $16 to $26 per acre across soybeans, corn, tobacco, and a growing vineyard industry. Reciprocity with multiple neighboring states.',
    faqs: [
      { question: 'What does drone spraying cost in Virginia?', answer: 'Row crops $16 to $20 per acre. Tobacco $22 to $26. Vineyard work $24 to $30. Virginia rates are higher than the Corn Belt due to smaller fields and fewer operators.' },
      { question: 'Is there really no renewal fee?', answer: 'Correct. Virginia eliminated the renewal fee in 2022. You pay a $25 non-refundable application once, then attend biennial recertification sessions. One of the cheapest ongoing licensing structures nationally.' },
      { question: 'Is the Virginia wine industry a drone opportunity?', answer: 'Growing. Approximately 4,000 acres of vineyards across the state, primarily in the Piedmont and Shenandoah Valley. Hillside blocks and small field sizes make drones more practical than airblast in many Virginia vineyards.' },
      { question: 'Does Virginia have reciprocal licensing?', answer: 'Yes, with KY, NC, SC, WV, MD, and DE. Reciprocal certificate is $70 for 2 years.' },
      { question: 'What FAA documentation does VDACS require?', answer: 'You must provide both FAA Part 107 and Part 137 documentation to VDACS as part of your aerial applicator certification. VDACS verifies these at the state level.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    abbreviation: 'WV',
    region: 'southeast',
    licensingAgency: 'West Virginia Department of Agriculture',
    licensingAgencyUrl: 'https://agriculture.wv.gov',
    aerialCategory: 'Category 14: Aerial',
    examsRequired: 'Core + Category 14. Contact WV DOA for fees.',
    examFees: 'Contact WV DOA at (304) 558-2209.',
    uniqueRules: [
      'Smallest agricultural acreage in the Southeast region.',
      'Mountainous terrain creates niche drone opportunities where ground equipment cannot operate.',
    ],
    reciprocityStates: ['KY', 'OH', 'PA', 'VA', 'MD'],
    renewalCycle: '3-year cycle.',
    ceRequirements: '20 CCUs per category per 3-year cycle.',
    droneSpecificCredential: false,
    droneGuidanceUrl: null,
    extensionUrl: 'https://extension.wvu.edu',
    topCrops: [
      { slug: 'corn', name: 'Corn', acreage: '50K acres', notes: 'Valley bottoms' },
    ],
    rateRange: '$18 to $28',
    neighboringStates: ['virginia', 'kentucky', 'ohio', 'pennsylvania', 'maryland'],
    description: 'West Virginia has the smallest agricultural acreage in the Southeast but mountainous terrain creates niche drone opportunities where ground equipment simply cannot operate. Rates are higher due to terrain complexity.',
    aeoBlock: 'West Virginia requires Category 14 (Aerial) with 20 CCUs per category per 3-year cycle. Agricultural acreage is the smallest in the Southeast, but mountainous terrain creates niche drone opportunities on steep pastures, orchards, and hay fields where ground equipment cannot operate. Rates run $18 to $28 per acre.',
    faqs: [
      { question: 'Is there much drone spray demand in West Virginia?', answer: 'Limited in total acreage but niche opportunities exist on steep pastures, small apple and peach orchards, and hay fields in mountain valleys where ground rigs cannot safely operate.' },
      { question: 'What does drone spraying cost in West Virginia?', answer: '$18 to $28 per acre. Higher than neighboring states due to small field sizes, steep terrain, and very few operators.' },
      { question: 'What license do I need?', answer: 'FAA Part 107, Part 137, and WV DOA Category 14 (Aerial). Contact WV DOA at (304) 558-2209 for current fees and exam schedule.' },
      { question: 'Does West Virginia have reciprocal licensing?', answer: 'Yes, with KY, OH, PA, VA, and MD. Contact WV DOA for procedures.' },
      { question: 'What makes West Virginia different from neighboring states?', answer: 'Terrain. West Virginia is almost entirely mountainous, which limits total ag acreage but makes drones the only practical aerial application method on many properties. Ground rigs and airplanes are both impractical on steep valley farms.' },
    ],
    lastReviewedAt: '2026-04-16',
  },
